import { useQuery } from "@tanstack/react-query";
import { useLocation } from "wouter";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { 
  BarChart3, 
  TrendingUp, 
  AlertCircle, 
  CheckCircle2, 
  AlertTriangle,
  Eye,
  FileText,
  Calendar,
  MapPin,
  Building2,
  Layout,
  ExternalLink,
  Lightbulb,
  Target,
  Zap,
  ChevronDown,
  ChevronUp
} from "lucide-react";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { useState } from "react";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  PieChart,
  Pie,
  Cell,
} from "recharts";

interface SEOStats {
  success: boolean;
  timestamp: string;
  systemStatus: {
    status: 'healthy' | 'degraded' | 'unhealthy';
    reason: string;
    expectedDaily: number;
    actualYesterday: number;
    failedGenerations7Days: number;
  };
  totals: {
    totalBlogs: number;
    totalAutoGenerated: number;
    totalViews: number;
  };
  blogsPerDay: Array<{
    date: string;
    count: number;
    autoGenerated: number;
  }>;
  topUrls: Array<{
    id: string;
    title: string;
    slug: string;
    city: string | null;
    sector: string | null;
    template: string | null;
    views: number;
    publishedAt: string;
  }>;
  distribution: {
    byCity: Array<{ city: string | null; count: number; totalViews: number }>;
    bySector: Array<{ sector: string | null; count: number; totalViews: number }>;
    byTemplate: Array<{ template: string | null; count: number; totalViews: number }>;
  };
  overusedCombinations: Array<{
    city: string | null;
    sector: string | null;
    count: number;
    posts: Array<{
      id: string;
      title: string;
      slug: string;
      views: number;
      publishedAt: string;
    }>;
  }>;
  recommendations: Array<{
    type: 'priority' | 'warning' | 'action';
    title: string;
    description: string;
    details?: { city?: string; sector?: string; count?: number };
  }>;
  coverage: {
    cities: Array<{ city: string; count: number; totalViews: number }>;
    sectors: Array<{ sector: string; count: number; totalViews: number }>;
  };
  recentLogs: Array<{
    batchId: string;
    executionDate: string;
    status: string;
    blogsGenerated: number;
    blogsSkipped: number;
    executionTimeMs: number | null;
    aiCallsCount: number;
    imageCallsCount: number;
    errors: string[];
    citiesUsed: string[];
    sectorsUsed: string[];
    source: string;
  }>;
}

const COLORS = ['#155d29', '#1a7535', '#1f8d40', '#24a54b', '#29bd56', '#2ed561', '#33ed6c', '#52f084', '#71f39c', '#90f6b4'];

interface CannibalizationGroupProps {
  combo: {
    city: string | null;
    sector: string | null;
    count: number;
    posts: Array<{
      id: string;
      title: string;
      slug: string;
      views: number;
      publishedAt: string;
    }>;
  };
  index: number;
}

function CannibalizationGroup({ combo, index }: CannibalizationGroupProps) {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <Collapsible open={isOpen} onOpenChange={setIsOpen}>
      <CollapsibleTrigger asChild>
        <button
          className="w-full flex items-center justify-between p-3 bg-yellow-100 hover:bg-yellow-200 rounded-lg border border-yellow-300 transition-colors"
          data-testid={`cannibalization-trigger-${index}`}
        >
          <div className="flex items-center gap-3">
            <Badge variant="outline" className="bg-yellow-200 border-yellow-400 text-yellow-800">
              {combo.count} posts
            </Badge>
            <span className="font-medium text-yellow-800 capitalize">
              {combo.city} / {combo.sector}
            </span>
          </div>
          {isOpen ? (
            <ChevronUp className="w-5 h-5 text-yellow-700" />
          ) : (
            <ChevronDown className="w-5 h-5 text-yellow-700" />
          )}
        </button>
      </CollapsibleTrigger>
      <CollapsibleContent>
        <div className="mt-2 space-y-2 pl-4 border-l-2 border-yellow-300">
          {combo.posts.map((post, postIndex) => (
            <div 
              key={post.id}
              className="flex items-center justify-between p-2 bg-white rounded border border-yellow-200 hover:border-yellow-400 transition-colors"
              data-testid={`cannibalization-post-${index}-${postIndex}`}
            >
              <div className="flex-1 min-w-0">
                <a
                  href={`/seo-blog/${post.slug}`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-[#155d29] hover:underline font-medium text-sm flex items-center gap-1 truncate"
                >
                  {post.title.length > 60 ? post.title.substring(0, 60) + '...' : post.title}
                  <ExternalLink className="w-3 h-3 flex-shrink-0" />
                </a>
                <p className="text-xs text-gray-500 mt-0.5">
                  {new Date(post.publishedAt).toLocaleDateString('es-VE')} | {post.views} vistas
                </p>
              </div>
              <div className="flex gap-1 ml-2">
                <a
                  href={`/seo-blog/${post.slug}`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="px-2 py-1 text-xs bg-gray-100 hover:bg-gray-200 rounded text-gray-700 transition-colors"
                  title="Ver artículo"
                >
                  Ver
                </a>
              </div>
            </div>
          ))}
          <div className="text-xs text-yellow-700 p-2 bg-yellow-50 rounded italic">
            Considera combinar artículos similares, desindexar los de menor rendimiento, o editar para diferenciar el contenido.
          </div>
        </div>
      </CollapsibleContent>
    </Collapsible>
  );
}

export default function SEOBlogAdmin() {
  const [, setLocation] = useLocation();
  
  const urlParams = new URLSearchParams(window.location.search);
  const token = urlParams.get('token');

  const { data, isLoading, error } = useQuery<SEOStats>({
    queryKey: ['/api/admin/seo-stats', token],
    queryFn: async () => {
      const response = await fetch(`/api/admin/seo-stats?token=${token}`);
      if (!response.ok) {
        throw new Error('Acceso no autorizado');
      }
      return response.json();
    },
    enabled: !!token,
    refetchInterval: 60000,
  });

  if (!token) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center p-4">
        <Card className="w-full max-w-md">
          <CardHeader className="text-center">
            <AlertCircle className="w-12 h-12 text-red-500 mx-auto mb-4" />
            <CardTitle>Acceso Restringido</CardTitle>
            <CardDescription>
              Se requiere un token de administrador para acceder a este panel.
            </CardDescription>
          </CardHeader>
        </Card>
      </div>
    );
  }

  if (isLoading) {
    return (
      <div className="min-h-screen bg-gray-50 p-6">
        <div className="max-w-7xl mx-auto space-y-6">
          <Skeleton className="h-12 w-64" />
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            {[1, 2, 3, 4].map((i) => (
              <Skeleton key={i} className="h-32" />
            ))}
          </div>
          <Skeleton className="h-80" />
        </div>
      </div>
    );
  }

  if (error || !data?.success) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center p-4">
        <Card className="w-full max-w-md">
          <CardHeader className="text-center">
            <AlertCircle className="w-12 h-12 text-red-500 mx-auto mb-4" />
            <CardTitle>Error de Acceso</CardTitle>
            <CardDescription>
              Token inválido o expirado. Verifica tu acceso.
            </CardDescription>
          </CardHeader>
        </Card>
      </div>
    );
  }

  const StatusIcon = () => {
    switch (data.systemStatus.status) {
      case 'healthy':
        return <CheckCircle2 className="w-8 h-8 text-green-600" />;
      case 'degraded':
        return <AlertTriangle className="w-8 h-8 text-yellow-600" />;
      case 'unhealthy':
        return <AlertCircle className="w-8 h-8 text-red-600" />;
    }
  };

  const statusColors = {
    healthy: 'bg-green-100 text-green-800 border-green-200',
    degraded: 'bg-yellow-100 text-yellow-800 border-yellow-200',
    unhealthy: 'bg-red-100 text-red-800 border-red-200',
  };

  const chartData = data.blogsPerDay.slice(0, 14).reverse();

  return (
    <div className="min-h-screen bg-gray-50" data-testid="seo-admin-panel">
      <div className="max-w-7xl mx-auto p-6 space-y-6">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold text-gray-900" data-testid="admin-title">
              Panel SEO TRANSERVICA
            </h1>
            <p className="text-gray-500 mt-1">
              Última actualización: {new Date(data.timestamp).toLocaleString('es-VE')}
            </p>
          </div>
          <a 
            href="/seo-blog" 
            className="flex items-center gap-2 text-[#155d29] hover:underline"
            data-testid="link-seo-blog"
          >
            <ExternalLink className="w-4 h-4" />
            Ver Blog SEO
          </a>
        </div>

        <Card className={`border-2 ${statusColors[data.systemStatus.status]}`} data-testid="status-card">
          <CardContent className="flex items-center gap-4 p-6">
            <StatusIcon />
            <div className="flex-1">
              <div className="flex items-center gap-2">
                <h2 className="text-xl font-semibold capitalize">
                  Estado: {data.systemStatus.status === 'healthy' ? 'Saludable' : 
                          data.systemStatus.status === 'degraded' ? 'Degradado' : 'No Saludable'}
                </h2>
                <Badge variant="outline" className={statusColors[data.systemStatus.status]}>
                  {data.systemStatus.status.toUpperCase()}
                </Badge>
              </div>
              <p className="text-sm mt-1">{data.systemStatus.reason}</p>
            </div>
            <div className="text-right">
              <p className="text-sm text-gray-600">Ayer</p>
              <p className="text-2xl font-bold">
                {data.systemStatus.actualYesterday}/{data.systemStatus.expectedDaily}
              </p>
              <p className="text-xs text-gray-500">blogs generados</p>
            </div>
          </CardContent>
        </Card>

        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          <Card data-testid="stat-total-blogs">
            <CardHeader className="flex flex-row items-center justify-between pb-2">
              <CardTitle className="text-sm font-medium text-gray-600">Total Blogs</CardTitle>
              <FileText className="w-4 h-4 text-[#155d29]" />
            </CardHeader>
            <CardContent>
              <p className="text-3xl font-bold text-gray-900">{data.totals.totalBlogs}</p>
              <p className="text-xs text-gray-500 mt-1">
                {data.totals.totalAutoGenerated} auto-generados
              </p>
            </CardContent>
          </Card>

          <Card data-testid="stat-total-views">
            <CardHeader className="flex flex-row items-center justify-between pb-2">
              <CardTitle className="text-sm font-medium text-gray-600">Total Vistas</CardTitle>
              <Eye className="w-4 h-4 text-[#155d29]" />
            </CardHeader>
            <CardContent>
              <p className="text-3xl font-bold text-gray-900">
                {data.totals.totalViews?.toLocaleString() || 0}
              </p>
              <p className="text-xs text-gray-500 mt-1">todas las URLs</p>
            </CardContent>
          </Card>

          <Card data-testid="stat-cities">
            <CardHeader className="flex flex-row items-center justify-between pb-2">
              <CardTitle className="text-sm font-medium text-gray-600">Ciudades</CardTitle>
              <MapPin className="w-4 h-4 text-[#155d29]" />
            </CardHeader>
            <CardContent>
              <p className="text-3xl font-bold text-gray-900">{data.distribution.byCity.length}</p>
              <p className="text-xs text-gray-500 mt-1">cubiertas</p>
            </CardContent>
          </Card>

          <Card data-testid="stat-sectors">
            <CardHeader className="flex flex-row items-center justify-between pb-2">
              <CardTitle className="text-sm font-medium text-gray-600">Sectores</CardTitle>
              <Building2 className="w-4 h-4 text-[#155d29]" />
            </CardHeader>
            <CardContent>
              <p className="text-3xl font-bold text-gray-900">{data.distribution.bySector.length}</p>
              <p className="text-xs text-gray-500 mt-1">industriales</p>
            </CardContent>
          </Card>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <Card data-testid="chart-daily">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <BarChart3 className="w-5 h-5 text-[#155d29]" />
                Blogs Generados por Día
              </CardTitle>
              <CardDescription>Últimos 14 días</CardDescription>
            </CardHeader>
            <CardContent>
              <ResponsiveContainer width="100%" height={250}>
                <BarChart data={chartData}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis 
                    dataKey="date" 
                    tickFormatter={(value) => {
                      const date = new Date(value);
                      return `${date.getDate()}/${date.getMonth() + 1}`;
                    }}
                    fontSize={12}
                  />
                  <YAxis fontSize={12} />
                  <Tooltip 
                    labelFormatter={(value) => new Date(value).toLocaleDateString('es-VE')}
                    formatter={(value: number, name: string) => [
                      value,
                      name === 'autoGenerated' ? 'Auto-generados' : 'Total'
                    ]}
                  />
                  <Bar dataKey="autoGenerated" fill="#155d29" name="autoGenerated" />
                </BarChart>
              </ResponsiveContainer>
            </CardContent>
          </Card>

          <Card data-testid="chart-distribution">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Layout className="w-5 h-5 text-[#155d29]" />
                Distribución por Template
              </CardTitle>
              <CardDescription>Tipos de contenido generado</CardDescription>
            </CardHeader>
            <CardContent>
              <ResponsiveContainer width="100%" height={250}>
                <PieChart>
                  <Pie
                    data={data.distribution.byTemplate.filter(t => t.template)}
                    dataKey="count"
                    nameKey="template"
                    cx="50%"
                    cy="50%"
                    outerRadius={80}
                    label={({ template, count }) => `${template}: ${count}`}
                  >
                    {data.distribution.byTemplate.map((_, index) => (
                      <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                    ))}
                  </Pie>
                  <Tooltip />
                </PieChart>
              </ResponsiveContainer>
            </CardContent>
          </Card>
        </div>

        <Card data-testid="table-top-urls">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <TrendingUp className="w-5 h-5 text-[#155d29]" />
              Top 10 URLs por Vistas
            </CardTitle>
            <CardDescription>Artículos con mejor rendimiento</CardDescription>
          </CardHeader>
          <CardContent>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead className="w-[50px]">#</TableHead>
                  <TableHead>Título</TableHead>
                  <TableHead>Ciudad</TableHead>
                  <TableHead>Sector</TableHead>
                  <TableHead>Template</TableHead>
                  <TableHead className="text-right">Vistas</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {data.topUrls.map((url, index) => (
                  <TableRow key={url.id} data-testid={`row-top-url-${index}`}>
                    <TableCell className="font-medium">{index + 1}</TableCell>
                    <TableCell>
                      <a 
                        href={`/seo-blog/${url.slug}`}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-[#155d29] hover:underline flex items-center gap-1"
                      >
                        {url.title.length > 50 ? url.title.substring(0, 50) + '...' : url.title}
                        <ExternalLink className="w-3 h-3" />
                      </a>
                    </TableCell>
                    <TableCell>
                      <Badge variant="outline">{url.city || '-'}</Badge>
                    </TableCell>
                    <TableCell>
                      <Badge variant="secondary">{url.sector || '-'}</Badge>
                    </TableCell>
                    <TableCell>{url.template || '-'}</TableCell>
                    <TableCell className="text-right font-semibold">
                      {url.views.toLocaleString()}
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </CardContent>
        </Card>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <Card data-testid="table-by-city">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <MapPin className="w-5 h-5 text-[#155d29]" />
                Distribución por Ciudad
              </CardTitle>
            </CardHeader>
            <CardContent>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Ciudad</TableHead>
                    <TableHead className="text-right">Posts</TableHead>
                    <TableHead className="text-right">Vistas</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {data.distribution.byCity.slice(0, 10).map((city, index) => (
                    <TableRow key={index} data-testid={`row-city-${index}`}>
                      <TableCell className="capitalize">{city.city || 'Sin ciudad'}</TableCell>
                      <TableCell className="text-right">{city.count}</TableCell>
                      <TableCell className="text-right">{city.totalViews?.toLocaleString() || 0}</TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </CardContent>
          </Card>

          <Card data-testid="table-by-sector">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Building2 className="w-5 h-5 text-[#155d29]" />
                Distribución por Sector
              </CardTitle>
            </CardHeader>
            <CardContent>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Sector</TableHead>
                    <TableHead className="text-right">Posts</TableHead>
                    <TableHead className="text-right">Vistas</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {data.distribution.bySector.map((sector, index) => (
                    <TableRow key={index} data-testid={`row-sector-${index}`}>
                      <TableCell className="capitalize">{sector.sector || 'Sin sector'}</TableCell>
                      <TableCell className="text-right">{sector.count}</TableCell>
                      <TableCell className="text-right">{sector.totalViews?.toLocaleString() || 0}</TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </div>

        {data.recommendations && data.recommendations.length > 0 && (
          <Card className="border-[#155d29] border-2 bg-green-50" data-testid="recommendations-card">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-[#155d29]">
                <Lightbulb className="w-5 h-5" />
                Próximos Pasos Sugeridos
              </CardTitle>
              <CardDescription className="text-green-700">
                Recomendaciones calculadas automáticamente basadas en los datos actuales
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-3">
                {data.recommendations.map((rec, index) => (
                  <div 
                    key={index} 
                    className={`p-4 rounded-lg border-l-4 ${
                      rec.type === 'priority' ? 'bg-blue-50 border-blue-500' :
                      rec.type === 'warning' ? 'bg-yellow-50 border-yellow-500' :
                      'bg-red-50 border-red-500'
                    }`}
                    data-testid={`recommendation-${index}`}
                  >
                    <div className="flex items-start gap-3">
                      {rec.type === 'priority' && <Target className="w-5 h-5 text-blue-600 mt-0.5 flex-shrink-0" />}
                      {rec.type === 'warning' && <AlertTriangle className="w-5 h-5 text-yellow-600 mt-0.5 flex-shrink-0" />}
                      {rec.type === 'action' && <Zap className="w-5 h-5 text-red-600 mt-0.5 flex-shrink-0" />}
                      <div>
                        <h4 className={`font-semibold ${
                          rec.type === 'priority' ? 'text-blue-800' :
                          rec.type === 'warning' ? 'text-yellow-800' :
                          'text-red-800'
                        }`}>
                          {rec.title}
                        </h4>
                        <p className="text-sm text-gray-700 mt-1">{rec.description}</p>
                        {rec.details && (
                          <div className="flex gap-2 mt-2">
                            {rec.details.city && (
                              <Badge variant="outline" className="text-xs">
                                <MapPin className="w-3 h-3 mr-1" />
                                {rec.details.city}
                              </Badge>
                            )}
                            {rec.details.sector && (
                              <Badge variant="outline" className="text-xs">
                                <Building2 className="w-3 h-3 mr-1" />
                                {rec.details.sector}
                              </Badge>
                            )}
                            {rec.details.count !== undefined && (
                              <Badge variant="secondary" className="text-xs">
                                {rec.details.count} posts
                              </Badge>
                            )}
                          </div>
                        )}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        )}

        {data.overusedCombinations.length > 0 && (
          <Card className="border-yellow-200 bg-yellow-50" data-testid="alert-cannibalization">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-yellow-800">
                <AlertTriangle className="w-5 h-5" />
                Alerta de Canibalización SEO - Posts Detallados
              </CardTitle>
              <CardDescription className="text-yellow-700">
                Combinaciones ciudad/sector con 3+ posts. Haz clic para ver los artículos y decidir si desindexar/combinar/editar.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                {data.overusedCombinations.map((combo, index) => (
                  <CannibalizationGroup key={index} combo={combo} index={index} />
                ))}
              </div>
            </CardContent>
          </Card>
        )}

        <Card data-testid="table-logs">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Calendar className="w-5 h-5 text-[#155d29]" />
              Logs de Generación Recientes
            </CardTitle>
            <CardDescription>Últimas 10 ejecuciones del sistema</CardDescription>
          </CardHeader>
          <CardContent>
            {data.recentLogs.length === 0 ? (
              <p className="text-gray-500 text-center py-4">No hay logs de generación registrados</p>
            ) : (
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Fecha</TableHead>
                    <TableHead>Estado</TableHead>
                    <TableHead className="text-right">Generados</TableHead>
                    <TableHead className="text-right">Omitidos</TableHead>
                    <TableHead className="text-right">Tiempo</TableHead>
                    <TableHead>Ciudades</TableHead>
                    <TableHead>Errores</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {data.recentLogs.map((log, index) => (
                    <TableRow key={index} data-testid={`row-log-${index}`}>
                      <TableCell>
                        {new Date(log.executionDate).toLocaleString('es-VE', {
                          day: '2-digit',
                          month: '2-digit',
                          hour: '2-digit',
                          minute: '2-digit'
                        })}
                      </TableCell>
                      <TableCell>
                        <Badge 
                          variant={log.status === 'completed' ? 'default' : 'destructive'}
                          className={log.status === 'completed' ? 'bg-green-600' : ''}
                        >
                          {log.status}
                        </Badge>
                      </TableCell>
                      <TableCell className="text-right font-semibold">{log.blogsGenerated}</TableCell>
                      <TableCell className="text-right">{log.blogsSkipped}</TableCell>
                      <TableCell className="text-right">
                        {log.executionTimeMs ? `${(log.executionTimeMs / 1000).toFixed(1)}s` : '-'}
                      </TableCell>
                      <TableCell>
                        <span className="text-xs text-gray-500">
                          {log.citiesUsed.slice(0, 3).join(', ')}
                          {log.citiesUsed.length > 3 && '...'}
                        </span>
                      </TableCell>
                      <TableCell>
                        {log.errors.length > 0 ? (
                          <Badge variant="destructive">{log.errors.length}</Badge>
                        ) : (
                          <span className="text-gray-400">-</span>
                        )}
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            )}
          </CardContent>
        </Card>

        <footer className="text-center text-gray-500 text-sm py-4">
          Panel Admin SEO TRANSERVICA &copy; {new Date().getFullYear()}
        </footer>
      </div>
    </div>
  );
}
