import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation object
const translations = {
  es: {
    // Navigation
    'nav.home': 'HOME',
    'nav.services': 'SERVICIOS',
    'nav.projects': 'PROYECTOS',
    'nav.company': 'COMPAÑÍA',
    'nav.contact': 'CONTACTO',
    'nav.quote': 'COTIZAR',
    'nav.blog': 'BLOG',
    
    // Hero Section
    'hero.title': 'Transporte de Cargas Excepcionales Venezuela - Hasta 1,100 Toneladas',
    'hero.subtitle': '40+ Años Especializados en Movilización de Cargas Pesadas y Sobredimensionadas',
    'hero.description': 'Especializados en Movilización de Cargas Pesadas y Sobredimensionadas hasta 1,100 toneladas con trailers Modulares Hidráulicos de última generación.',
    'hero.cta': 'SOLICITAR COTIZACIÓN',
    'hero.video': 'VER VIDEO CORPORATIVO',
    
    // Services Section
    'services.title': 'Servicios de Transporte Especializado en Venezuela',
    'services.subtitle': 'Soluciones especializadas en transporte de cargas excepcionales',
    'services.transport.title': 'Transporte de Cargas Excepcionales',
    'services.transport.description': 'Movilización de cargas hasta 1,100 toneladas con trailers modulares hidráulicos SCHEUERLE y COMETTO de última generación.',
    'services.transport.feature1': 'Hasta 1,100 toneladas',
    'services.transport.feature2': 'Trailers modulares',
    'services.transport.feature3': 'Rutas especializadas',
    'services.transport.feature4': 'Escolta especializada',
    'services.cranes.title': 'Izamiento con Grúas Especializadas',
    'services.cranes.description': 'Servicios de izamiento con Grúas Móviles Telescópicas y Sobre Orugas para proyectos industriales complejos.',
    'services.cranes.feature1': 'Grúas telescópicas',
    'services.cranes.feature2': 'Grúas sobre orugas',
    'services.cranes.feature3': 'Izamiento preciso',
    'services.cranes.feature4': 'Operadores certificados',
    'services.logistics.title': 'Logística de Ingeniería Completa',
    'services.logistics.description': 'Planificación integral de proyectos de transporte con estudios de factibilidad y coordinación multimodal.',
    'services.logistics.feature1': 'Estudios de factibilidad',
    'services.logistics.feature2': 'Planificación de rutas',
    'services.logistics.feature3': 'Coordinación multimodal',
    'services.logistics.feature4': 'Gestión de proyecto',
    'services.permits.title': 'Gestión de Permisos INTT',
    'services.permits.description': 'Tramitación completa de permisos ante el Instituto Nacional de Transporte Terrestre y autoridades competentes.',
    'services.permits.feature1': 'Permisos INTT',
    'services.permits.feature2': 'Documentación completa',
    'services.permits.feature3': 'Gestión rápida',
    'services.permits.feature4': 'Cumplimiento normativo',
    'services.feasibility.title': 'Estudios de Factibilidad Técnica',
    'services.feasibility.description': 'Análisis detallado de viabilidad técnica para garantizar el éxito de proyectos de transporte especializado.',
    'services.feasibility.feature1': 'Análisis de rutas',
    'services.feasibility.feature2': 'Evaluación estructural',
    'services.feasibility.feature3': 'Estudios de carga',
    'services.feasibility.feature4': 'Recomendaciones técnicas',
    'services.multimodal.title': 'Coordinación Multimodal',
    'services.multimodal.description': 'Servicios integrados de transporte terrestre, marítimo y ferroviario para proyectos internacionales.',
    'services.multimodal.feature1': 'Transporte terrestre',
    'services.multimodal.feature2': 'Coordinación marítima',
    'services.multimodal.feature3': 'Transporte ferroviario',
    'services.multimodal.feature4': 'Logística internacional',
    'services.consult': 'Consultar',
    'services.quote': 'Cotizar',
    'services.cta.title': '¿Necesita Transportar Cargas Excepcionales?',
    'services.cta.subtitle': 'Permítanos Evaluar su Proyecto y Ofrecerle la Mejor Solución de Transporte de Carga Especializado',
    'services.cta.quote': 'Solicitar Cotización Ahora',
    'services.cta.call': 'Hablar con un Especialista',
    'services.cta': 'SOLICITAR INFORMACIÓN',
    'services.watch': 'VER SERVICIOS',
    
    // About Section
    'about.title': 'SOBRE TRANSERVICA',
    'about.subtitle': '40 años transportando el futuro de Venezuela',
    'about.description': 'Somos una empresa venezolana especializada en transporte de cargas excepcionales con más de 4 décadas de experiencia. Contamos con tecnología alemana SCHEUERLE y un equipo altamente calificado para manejar los proyectos más desafiantes.',
    'about.experience': '40+ Años de Experiencia',
    'about.projects': '1000+ Proyectos Exitosos',
    'about.capacity': '1,100 Toneladas Capacidad',
    'about.equipment': 'Tecnología Alemana',
    'about.cta': 'CONOCER MÁS',
    'about.video': 'VER VIDEO CORPORATIVO',
    'about.benefit1.title': 'Capacidad excepcional hasta 1,100 toneladas',
    'about.benefit1.desc': 'Equipos modulares hidráulicos alemanes de última generación.',
    'about.benefit2.title': 'Cobertura nacional con experiencia comprobada',
    'about.benefit2.desc': '40 años transportando el futuro de Venezuela con éxito.',
    'about.benefit3.title': 'Plataforma integral con soporte 24/7',
    'about.benefit3.desc': 'Seguimiento completo y especialistas disponibles siempre.',
    'about.benefit4.title': 'Soporte personalizado con humanos reales',
    'about.benefit4.desc': 'Especialistas en logística dedicados disponibles en cualquier momento.',
    'about.mission.title': 'Misión',
    'about.mission.text': 'Prestación del servicio de movilización e izamiento de cargas sobredimensionadas mediante el cumplimiento de criterios de seguridad, garantía y confiabilidad, anticipando y respondiendo eficazmente las necesidades de nuestros clientes, procurando el bienestar de nuestros trabajadores y maximizando la productividad.',
    'about.vision.title': 'Visión',
    'about.vision.text': 'Ser una empresa reconocida nacional e internacionalmente en la prestación de servicios de movilización e izamiento de cargas sobredimensionadas, con personal calificado, mejoramiento continuo, aprovechamiento de oportunidades y satisfacción permanente de clientes.',
    'about.cta.title': 'Múltiples Cargas Excepcionales. Una Plataforma. Cero Complicaciones.',
    'about.cta.subtitle': 'Compare cotizaciones de transporte pesado y sobredimensionado, reserve al instante y rastree en tiempo real — todo con TRANSERVICA.',
    'about.cta.quote': 'OBTENER COTIZACIÓN INSTANTÁNEA',
    'about.cta.call': 'HABLAR CON UN ESPECIALISTA',
    
    // Contact Section
    'contact.title': 'Solicita tu Cotización',
    'contact.subtitle': 'Cuéntanos sobre tu proyecto y te proporcionaremos una solución personalizada con la mejor propuesta del mercado.',
    'contact.form.name': 'Nombre',
    'contact.form.name.placeholder': 'Tu nombre completo',
    'contact.form.email': 'Email',
    'contact.form.email.placeholder': 'tu@email.com',
    'contact.form.phone': 'Teléfono',
    'contact.form.phone.placeholder': '+58 424 123 4567',
    'contact.form.company': 'Empresa',
    'contact.form.company.placeholder': 'Nombre de la empresa',
    'contact.form.cargo': 'Tipo de Carga',
    'contact.form.cargo.placeholder': 'Seleccionar tipo',
    'contact.form.cargo.industrial': 'Equipos Industriales',
    'contact.form.cargo.machinery': 'Maquinaria Pesada',
    'contact.form.cargo.turbines': 'Turbinas',
    'contact.form.cargo.oil': 'Equipos Petroleros',
    'contact.form.cargo.naval': 'Construcción Naval',
    'contact.form.cargo.others': 'Otros',
    'contact.form.weight': 'Peso Estimado (Toneladas)',
    'contact.form.weight.placeholder': '100',
    'contact.form.origin': 'Origen',
    'contact.form.origin.placeholder': 'Ciudad de origen',
    'contact.form.destination': 'Destino',
    'contact.form.destination.placeholder': 'Ciudad de destino',
    'contact.form.description': 'Descripción del Proyecto',
    'contact.form.description.placeholder': 'Describe tu proyecto, dimensiones, características especiales, fecha requerida, etc.',
    'contact.form.message': 'Mensaje',
    'contact.form.submit': 'Solicitar Cotización Gratuita',
    'contact.form.sending': 'Enviando...',
    'contact.info.title': 'Información de Contacto',
    'contact.info.phones': 'Teléfonos Principales',
    'contact.info.email': 'Dirección Comercial',
    'contact.info.executive': 'Dirección Ejecutiva',
    // Hero Stats - Critical for translation
    'hero.stats.years': '40',
    'hero.stats.years.title': 'Años de Experiencia',
    'hero.stats.years.subtitle': 'Líder en transporte especializado',
    'hero.stats.capacity': '1100',
    'hero.stats.capacity.title': 'Toneladas de Capacidad',
    'hero.stats.capacity.subtitle': 'Tecnología especializada',
    'hero.stats.reliability': '100%',
    'hero.stats.reliability.title': 'Confiabilidad',
    'hero.stats.reliability.subtitle': 'Proyectos exitosos',
    // Projects Gallery  
    'projects.title': 'Galería de Proyectos',
    'projects.subtitle': 'Más de 40 años transportando cargas excepcionales hasta 1,100 toneladas. Conoce algunos de nuestros proyectos más destacados realizados con equipos especializados y tecnología de vanguardia.',
    'equipment.title': 'Nuestros Equipos Especializados para Izamiento y Transportes de Carga Excepcionales y Sobredimensionadas',
    'equipment.subtitle': 'Tecnología especializada para transporte con equipos alemanes',
    'equipment.cta.title': '¿Necesita Equipos Especializados para su Proyecto?',
    'equipment.cta.subtitle': 'Contamos con la flota más moderna de Venezuela para transporte de cargas excepcionales',
    'equipment.cta.button': 'SOLICITAR COTIZACIÓN',
    
    // FAQ Section
    'faq.title': 'Preguntas Frecuentes',
    'faq.subtitle': 'Resuelve tus dudas sobre nuestros servicios de transporte especializado',
    'faq.q1': '¿Cuál es la capacidad máxima de carga que pueden transportar?',
    'faq.a1': 'Nuestra flota especializada puede transportar hasta 1,100 toneladas utilizando remolques modulares hidráulicos de última generación.',
    'faq.q2': '¿Qué tipo de permisos necesito para mi carga?',
    'faq.a2': 'Nosotros nos encargamos de toda la gestión de permisos especiales, documentación y coordinación con autoridades competentes.',
    'faq.q3': '¿Cubren todo el territorio venezolano?',
    'faq.a3': 'Sí, ofrecemos servicios de transporte especializado en todo el territorio nacional con rutas optimizadas y logística integral.',
    'faq.q4': '¿Qué incluye el servicio de transporte?',
    'faq.a4': 'Incluye planificación de ruta, permisos, seguros, carga/descarga, escolta especializada y monitoreo en tiempo real.',
    
    // Equipment items
    'equipment.item1.name': 'Combinaciones de modulares hidráulicos con un peso de hasta 1,100 toneladas',
    'equipment.item1.description': 'Tecnología especializada para el transporte de cargas excepcionales',
    'equipment.item1.capacity': '1,100 toneladas',
    'equipment.item1.feature1': 'Sistemas hidráulicos avanzados',
    'equipment.item1.feature2': 'Configuración modular',
    'equipment.item1.feature3': 'Sistemas digitales',
    'equipment.item1.feature4': 'Suspensión adaptativa',
    'equipment.item2.name': 'Sistemas Especializados hasta 1100 toneladas',
    'equipment.item2.description': 'Plataformas autopropulsadas de alta precisión para cargas críticas',
    'equipment.item2.capacity': 'hasta 1100 toneladas',
    'equipment.item2.feature1': 'Autopropulsado',
    'equipment.item2.feature2': 'Control de precisión',
    'equipment.item2.feature3': 'Sistemas de navegación',
    'equipment.item2.feature4': 'Operación remota',
    'equipment.item3.name': 'Grúas Móviles Telescópicas hasta 500 toneladas',
    'equipment.item3.description': 'Grúas Móviles de Alta Capacidad para Operaciones de Izamiento Especializado',
    'equipment.item3.capacity': 'hasta 500 toneladas',
    'equipment.item3.feature1': 'Alta movilidad',
    'equipment.item3.feature2': 'Controles digitales',
    'equipment.item3.feature3': 'Operadores certificados',
    'equipment.item4.name': 'Grúas sobre Orugas hasta 800 toneladas',
    'equipment.item4.description': 'Equipos Especializados para Izamiento en Terrenos Difíciles',
    'equipment.item4.capacity': 'hasta 800 toneladas',
    'equipment.item4.feature1': 'Base sobre orugas',
    'equipment.item4.feature2': 'Estabilidad superior',
    'equipment.item4.feature3': 'Alcance extendido',
    'equipment.item4.feature4': 'Configuración versátil',
    'equipment.item5.name': 'Camiones Especializados Variable',
    'equipment.item5.description': 'Alquiler de Flota de Camiones Especializados para Diferentes Tipos de Carga',
    'equipment.item5.capacity': 'Variable',
    'equipment.item5.feature1': 'Alta potencia',
    'equipment.item5.feature2': 'Transmisión especializada',
    'equipment.item5.feature3': 'Sistemas de seguridad',
    'equipment.item5.feature4': 'Mantenimiento preventivo',
    'equipment.item6.name': 'Equipos de Apoyo Diversas',
    'equipment.item6.description': 'Sistemas complementarios para operaciones complejas de transporte',
    'equipment.item6.capacity': 'Diversas',
    'equipment.item6.feature1': 'Sistemas de apoyo',
    'equipment.item6.feature2': 'Equipos auxiliares',
    'equipment.item6.feature3': 'Herramientas especializadas',
    'equipment.item6.feature4': 'Soporte técnico',
    'equipment.specs.button': 'Ver Especificaciones',
    'projects.1.title': 'Transporte Ferroviario Metro Caracas',
    'projects.1.weight': '280 toneladas',
    'projects.1.sector': 'Transporte Ferroviario',
    'projects.1.location': 'Puerto La Guaira - Caracas',
    'projects.1.description': 'Transporte especializado de vagones del Metro de Caracas con trailers modulares hidráulicos',
    'projects.2.title': 'Equipos Ferroviarios Protegidos',
    'projects.2.weight': '250 toneladas',
    'projects.2.sector': 'Transporte Ferroviario',
    'projects.2.location': 'Puerto Cabello - Interior',
    'projects.2.description': 'Vagones de metro con protección especial durante transporte terrestre',
    'projects.3.title': 'Convoy Ferroviario Multicar',
    'projects.3.weight': '450 toneladas',
    'projects.3.sector': 'Transporte Ferroviario',
    'projects.3.location': 'Operación Nacional',
    'projects.3.description': 'Múltiples vagones transportados simultáneamente con coordinación logística integral',
    'projects.4.title': 'Transporte Carretero Especializado',
    'projects.4.weight': '380 toneladas',
    'projects.4.sector': 'Logística Industrial',
    'projects.4.location': 'Rutas Nacionales',
    'projects.4.description': 'Convoy de transporte de cargas excepcionales por carreteras venezolanas',
    
    // Project CTA buttons
    'projects.cta.1': 'COTIZAR PROYECTO SIMILAR',
    'projects.cta.2': 'VER MÁS PROYECTOS', 
    'projects.cta.3': 'SOLICITAR INFORMACIÓN',
    'projects.cta.4': 'CONTACTAR ESPECIALISTA',
    'projects.cta.5': 'CONOCER CAPACIDADES',
    'projects.cta.6': 'EVALUAR MI CARGA',
    'projects.cta.7': 'PLANIFICAR TRANSPORTE',
    'projects.cta.8': 'CONSULTAR DISPONIBILIDAD',
    'projects.cta.9': 'OBTENER PRESUPUESTO',
    'projects.cta.10': 'ASESORÍA TÉCNICA GRATIS',
    'projects.cta.11': 'ESTUDIOS DE FACTIBILIDAD',
    'projects.cta.12': 'COORDINACIÓN LOGÍSTICA',
    
    // Project stats
    'projects.stats.of': 'de',
    'projects.stats.projects': 'proyectos',
    'projects.stats.years': 'años experiencia',
    'contact.info.address': 'Ubicación',
    'contact.whatsapp': 'Contactar por WhatsApp',
    'contact.address.full': 'Carretera Nacional Maracay Mariara Km 9, Mariara, Edo. Carabobo',
    
    // Footer
    'footer.description': 'Especializados en transporte de cargas excepcionales hasta 1,100 toneladas con trailers modulares hidráulicos. 40 años transportando el futuro de Venezuela con tecnología alemana de vanguardia.',
    
    // Footer sections
    'footer.pages.title': 'Páginas',
    'footer.pages.home': 'Inicio',
    'footer.pages.about': 'Nosotros',
    'footer.pages.services': 'Servicios',
    'footer.pages.projects': 'Proyectos',
    'footer.pages.contact': 'Contacto',
    
    'footer.resources.title': 'Recursos',
    'footer.resources.blog': 'Blog',
    'footer.resources.equipment': 'Equipos',
    'footer.resources.help': 'Centro de Ayuda',
    'footer.resources.specifications': 'Especificaciones',
    'footer.resources.testimonials': 'Testimonios',
    
    'footer.policies.privacy': 'Política de Protección de Datos',
    'footer.policies.security': 'Política de Seguridad Vial Integral',
    'footer.policies.management': 'Política Integrada de Gestión',
    
    'footer.legal.terms': 'Términos de Servicio',
    'footer.legal.privacy': 'Política de Privacidad',
    'footer.legal.cookies': 'Acuerdo de Cookies',
    'footer.legal.security': 'Política de Seguridad',
    
    'footer.social.title': 'Síguenos en',
    'footer.quote.button': 'SOLICITAR COTIZACIÓN',
    'footer.maps.button': 'VER EN GOOGLE MAPS',
    'footer.services.title': 'Servicios',
    'footer.services.transport': 'Transporte Especializado',
    'footer.services.engineering': 'Logística de Ingeniería',
    'footer.services.hydraulic': 'Modulares Hidráulicos',
    'footer.services.cranes': 'Grúas Grove y Liebherr',
    'footer.newsletter.title': 'Suscríbete a nuestro newsletter',
    'footer.newsletter.placeholder': 'Email de trabajo',
    'footer.newsletter.subscribe': 'Subscribirse',
    'footer.copyright': '© 2025 TRANSERVICA C.A. - Todos los Derechos Reservados.',
    'footer.rif': 'RIF: J-00207776-0 | 40 años transportando el futuro de Venezuela',
    'footer.follow': 'SEGUIR EN REDES',
    
    // Language Switcher
    'language.spanish': 'ESPAÑOL',
    'language.english': 'ENGLISH',
    
    // Blog
    'blog.title': 'TRANSERVICA BLOG',
    'blog.subtitle': 'Noticias y proyectos de transporte especializado',
    'blog.readMore': 'LEER MÁS',
    'blog.backToHome': 'VOLVER AL INICIO',
    'blog.section.badge': 'Blog Corporativo',
    'blog.section.title': 'NOTICIAS TRANSERVICA',
    'blog.section.description': 'Noticias y proyectos de Transporte de Carga Especializado',
    'blog.section.featured': 'Noticias y Proyectos Destacados',
    'blog.section.readFullArticle': 'Leer Artículo Completo',
    'blog.section.newsletter.title': 'Newsletter TRANSERVICA',
    'blog.section.newsletter.description': 'Recibe noticias exclusivas sobre proyectos de transporte especializado, equipos de última generación y normativas del sector',
    'blog.section.newsletter.placeholder': 'Ingresa tu email corporativo',
    'blog.section.newsletter.subscribe': 'Suscribirse al Blog',
    'blog.section.viewAll': 'Ver Todos los Artículos del Blog',
    'blog.section.cta.title': '¿Tienes un Proyecto Especializado?',
    'blog.section.cta.description': '40 años de experiencia nos respaldan. Nuestro equipo de ingenieros está listo para desarrollar la mejor solución logística para tu empresa',
    'blog.section.cta.consult': 'Consultar Proyecto',
    'blog.section.cta.services': 'Ver Servicios',
    
    // Legal Pages
    'legal.terms.title': 'Términos de Servicio',
    'legal.terms.description': 'Condiciones generales que rigen los servicios de transporte especializado de TRANSERVICA, C.A.',
    'legal.privacy.title': 'Política de Privacidad',
    'legal.privacy.description': 'Protección y tratamiento de datos personales en TRANSERVICA, C.A.',
    'legal.cookies.title': 'Acuerdo de Cookies',
    'legal.cookies.description': 'Información sobre el uso de cookies y tecnologías similares en nuestro sitio web',
    'legal.security.title': 'Política de Seguridad',
    'legal.security.description': 'Compromiso integral con la seguridad en transporte de cargas excepcionales',
    
    // Terms of Service Content
    'terms.acceptance.title': 'Aceptación de los Términos',
    'terms.acceptance.content1': 'Al contratar los servicios de TRANSERVICA, C.A. (en adelante "la Empresa"), el cliente acepta expresamente estos términos y condiciones. Estos términos constituyen un acuerdo legalmente vinculante entre el cliente y TRANSERVICA, C.A., empresa especializada en transporte de cargas excepcionales con 40 años de experiencia.',
    'terms.acceptance.content2': 'La utilización de nuestros servicios implica la aceptación total e incondicional de las presentes condiciones, las cuales prevalecerán sobre cualquier otra condición establecida por el cliente.',
    'terms.services.title': 'Descripción de Servicios',
    'terms.services.content1': 'TRANSERVICA, C.A. ofrece servicios especializados de transporte de cargas excepcionales hasta 1,100 toneladas, utilizando trailers modulares hidráulicos SCHEUERLE y COMETTO de última generación. Nuestros servicios incluyen:',
    'terms.services.item1': 'Transporte de cargas excepcionales y sobredimensionadas',
    'terms.services.item2': 'Servicios de grúas móviles y sobre orugas hasta 800 toneladas',
    'terms.services.item3': 'Logística integral y coordinación de proyectos especiales',
    'terms.services.item4': 'Estudios de factibilidad y planificación de rutas',
    'terms.services.item5': 'Servicios de izamiento y montaje especializado',
    'terms.services.content2': 'Todos los servicios se ejecutan bajo estrictos protocolos de seguridad y cumpliendo con la normativa venezolana e internacional aplicable.',
    'terms.responsibilities.title': 'Responsabilidades del Cliente',
    'terms.responsibilities.content1': 'El cliente se compromete a:',
    'terms.responsibilities.item1': 'Proporcionar información precisa y completa sobre las características de la carga',
    'terms.responsibilities.item2': 'Obtener todos los permisos y autorizaciones necesarias cuando sea requerido',
    'terms.responsibilities.item3': 'Facilitar el acceso a los puntos de carga y descarga en las condiciones acordadas',
    'terms.responsibilities.item4': 'Pagar los servicios según las condiciones comerciales establecidas',
    'terms.responsibilities.item5': 'Cumplir con las normas de seguridad y protocolos establecidos por TRANSERVICA',
    'terms.responsibilities.content2': 'El incumplimiento de estas obligaciones puede resultar en la suspensión del servicio y la facturación de costos adicionales.',
    'terms.limitations.title': 'Limitaciones de Responsabilidad',
    'terms.limitations.content1': 'TRANSERVICA, C.A. mantiene pólizas de seguro que cubren los servicios prestados según los términos y límites establecidos en las mismas. La responsabilidad de la empresa se limita a:',
    'terms.limitations.item1': 'Daños causados por negligencia comprobada en la prestación del servicio',
    'terms.limitations.item2': 'Límites establecidos en las pólizas de seguro vigentes',
    'terms.limitations.item3': 'Exclusión de lucro cesante, daños indirectos o consecuenciales',
    'terms.limitations.content2': 'No se acepta responsabilidad por demoras causadas por factores externos como condiciones climáticas, restricciones gubernamentales, o circunstancias de fuerza mayor.',
    'terms.payment.title': 'Condiciones de Pago',
    'terms.payment.content1': 'Los servicios se facturan según las tarifas vigentes al momento de la prestación del servicio. Las condiciones de pago incluyen:',
    'terms.payment.item1': 'Anticipo del 50% al momento de la confirmación del servicio',
    'terms.payment.item2': 'Saldo restante contra entrega o según términos acordados',
    'terms.payment.item3': 'Facturación de servicios adicionales no contemplados en la cotización original',
    'terms.payment.item4': 'Penalidades por pagos tardíos según condiciones comerciales',
    'terms.forceMajeure.title': 'Fuerza Mayor',
    'terms.forceMajeure.content': 'TRANSERVICA, C.A. no será responsable por el incumplimiento de sus obligaciones cuando este se deba a causas de fuerza mayor, incluyendo pero no limitándose a: desastres naturales, conflictos laborales, restricciones gubernamentales, pandemias, o cualquier otra circunstancia fuera del control razonable de la empresa.',
    'terms.modifications.title': 'Modificaciones',
    'terms.modifications.content': 'TRANSERVICA, C.A. se reserva el derecho de modificar estos términos y condiciones en cualquier momento. Las modificaciones entrarán en vigor inmediatamente después de su publicación en el sitio web oficial de la empresa. Se recomienda revisar periódicamente estos términos.',
    'terms.contact.title': 'Información de Contacto',
    
    // Privacy Policy Content
    'privacy.introduction.title': 'Introducción',
    'privacy.introduction.content1': 'TRANSERVICA, C.A., empresa especializada en transporte de cargas excepcionales, reconoce la importancia de proteger la privacidad y los datos personales de nuestros clientes, proveedores, empleados y visitantes de nuestro sitio web.',
    'privacy.introduction.content2': 'Esta Política de Privacidad establece cómo recopilamos, utilizamos, almacenamos y protegemos la información personal que nos proporciona, en cumplimiento con las leyes venezolanas aplicables y las mejores prácticas internacionales.',
    'privacy.collection.title': 'Recopilación de Información',
    'privacy.collection.content1': 'Recopilamos información personal de las siguientes maneras:',
    'privacy.collection.direct.title': 'Información Directa',
    'privacy.collection.direct.item1': 'Datos proporcionados en formularios de contacto y cotizaciones',
    'privacy.collection.direct.item2': 'Información comercial para la prestación de servicios',
    'privacy.collection.direct.item3': 'Datos de empleados y colaboradores',
    'privacy.collection.direct.item4': 'Registros de comunicaciones telefónicas y por email',
    'privacy.collection.automatic.title': 'Información Automática',
    'privacy.collection.automatic.item1': 'Dirección IP y datos de navegación en nuestro sitio web',
    'privacy.collection.automatic.item2': 'Cookies y tecnologías similares',
    'privacy.collection.automatic.item3': 'Información de dispositivos y preferencias de navegación',
    'privacy.collection.automatic.item4': 'Registros de acceso y uso del sitio web',
    'privacy.usage.title': 'Uso de la Información',
    'privacy.usage.content1': 'Utilizamos la información recopilada para los siguientes propósitos:',
    'privacy.usage.item1': 'Prestación de servicios de transporte especializado',
    'privacy.usage.item2': 'Comunicación con clientes y seguimiento de proyectos',
    'privacy.usage.item3': 'Procesamiento de cotizaciones y facturación',
    'privacy.usage.item4': 'Mejora de nuestros servicios y experiencia del usuario',
    'privacy.usage.item5': 'Cumplimiento de obligaciones legales y regulatorias',
    'privacy.usage.item6': 'Marketing directo y comunicaciones comerciales (con consentimiento)',
    'privacy.usage.item7': 'Análisis estadísticos y estudios de mercado internos',
    'privacy.usage.content2': 'No utilizamos la información personal para fines distintos a los mencionados sin obtener el consentimiento expreso del titular de los datos.',
    'privacy.protection.title': 'Protección de Datos',
    'privacy.protection.content1': 'TRANSERVICA implementa medidas técnicas y organizativas apropiadas para proteger los datos personales contra:',
    'privacy.protection.item1': 'Acceso no autorizado, alteración, divulgación o destrucción',
    'privacy.protection.item2': 'Pérdida accidental o tratamiento ilícito',
    'privacy.protection.item3': 'Transferencias no autorizadas',
    'privacy.protection.security.title': 'Medidas de Seguridad',
    'privacy.protection.security.item1': 'Cifrado de datos sensibles en tránsito y almacenamiento',
    'privacy.protection.security.item2': 'Control de acceso basado en roles y necesidad de conocer',
    'privacy.protection.security.item3': 'Monitoreo continuo de sistemas y detección de anomalías',
    'privacy.protection.security.item4': 'Capacitación regular del personal en protección de datos',
    'privacy.protection.security.item5': 'Respaldo seguro y planes de continuidad del negocio',
    'privacy.sharing.title': 'Compartir Información',
    'privacy.sharing.content1': 'TRANSERVICA no vende, alquila o comparte información personal con terceros, excepto en las siguientes circunstancias:',
    'privacy.sharing.item1': 'Con proveedores de servicios que requieren la información para completar proyectos',
    'privacy.sharing.item2': 'Cuando sea requerido por autoridades legales competentes',
    'privacy.sharing.item3': 'Para proteger los derechos, propiedad o seguridad de la empresa',
    'privacy.sharing.item4': 'Con el consentimiento explícito del titular de los datos',
    'privacy.sharing.item5': 'En caso de fusión, adquisición o transferencia de activos empresariales',
    'privacy.sharing.content2': 'Cualquier tercero que acceda a información personal debe comprometerse a mantener el mismo nivel de protección establecido en esta política.',
    'privacy.rights.title': 'Derechos del Titular',
    'privacy.rights.content1': 'Usted tiene derecho a:',
    'privacy.rights.item1': 'Acceder a sus datos personales que mantenemos',
    'privacy.rights.item2': 'Rectificar información inexacta o incompleta',
    'privacy.rights.item3': 'Solicitar la eliminación de sus datos personales',
    'privacy.rights.item4': 'Oponerse al tratamiento de sus datos para marketing directo',
    'privacy.rights.item5': 'Solicitar la portabilidad de sus datos',
    'privacy.rights.item6': 'Presentar quejas ante autoridades de protección de datos',
    'privacy.rights.content2': 'Para ejercer estos derechos, puede contactarnos a través de los medios proporcionados al final de esta política.',
    'privacy.retention.title': 'Retención de Datos',
    'privacy.retention.content1': 'Conservamos los datos personales durante el tiempo necesario para cumplir con los propósitos establecidos en esta política, considerando:',
    'privacy.retention.item1': 'Duración de la relación comercial o contractual',
    'privacy.retention.item2': 'Obligaciones legales de conservación de registros',
    'privacy.retention.item3': 'Necesidades de defensa legal y resolución de disputas',
    'privacy.retention.item4': 'Propósitos estadísticos o de archivo de interés público',
    'privacy.updates.title': 'Actualizaciones',
    'privacy.updates.content': 'Esta Política de Privacidad puede ser actualizada periódicamente para reflejar cambios en nuestras prácticas, servicios o requisitos legales. Las modificaciones significativas serán notificadas a través de nuestro sitio web y otros medios apropiados.',
    'privacy.contact.title': 'Contacto para Asuntos de Privacidad',
    
    // Cookies Policy Content
    'cookies.what.title': '¿Qué son las Cookies?',
    'cookies.what.content1': 'Las cookies son pequeños archivos de texto que se almacenan en su dispositivo cuando visita nuestro sitio web. Estas tecnologías nos permiten reconocer su navegador y dispositivo, recordar sus preferencias y mejorar su experiencia de navegación.',
    'cookies.what.content2': 'TRANSERVICA, C.A. utiliza cookies para proporcionar una experiencia web optimizada, analizar el uso del sitio y personalizar el contenido según las necesidades de nuestros visitantes.',
    'cookies.types.title': 'Tipos de Cookies que Utilizamos',
    'cookies.types.essential.title': 'Cookies Esenciales',
    'cookies.types.essential.content': 'Estas cookies son necesarias para el funcionamiento básico del sitio web y no pueden ser desactivadas. Incluyen:',
    'cookies.types.essential.item1': 'Cookies de sesión para mantener la funcionalidad durante su visita',
    'cookies.types.essential.item2': 'Cookies de seguridad para proteger contra ataques maliciosos',
    'cookies.types.essential.item3': 'Cookies de preferencias de idioma y configuración regional',
    'cookies.types.essential.item4': 'Cookies de formularios para recordar información ingresada',
    'cookies.types.analytics.title': 'Cookies Analíticas',
    'cookies.types.analytics.content': 'Nos ayudan a entender cómo los visitantes interactúan con nuestro sitio web:',
    'cookies.types.analytics.item1': 'Google Analytics para análisis de tráfico y comportamiento',
    'cookies.types.analytics.item2': 'Seguimiento de páginas visitadas y tiempo de permanencia',
    'cookies.types.analytics.item3': 'Identificación de contenido más popular y relevante',
    'cookies.types.analytics.item4': 'Análisis de rutas de navegación y puntos de salida',
    'cookies.types.functional.title': 'Cookies de Funcionalidad',
    'cookies.types.functional.content': 'Mejoran la funcionalidad y personalización del sitio:',
    'cookies.types.functional.item1': 'Recordar preferencias de idioma y región',
    'cookies.types.functional.item2': 'Mantener configuraciones de accesibilidad',
    'cookies.types.functional.item3': 'Personalizar contenido basado en interacciones previas',
    'cookies.types.functional.item4': 'Facilitar el uso de formularios de contacto',
    'cookies.management.title': 'Gestión de Cookies',
    'cookies.management.content': 'Usted tiene control total sobre las cookies utilizadas en nuestro sitio web. Puede gestionar sus preferencias de las siguientes maneras:',
    'cookies.management.browser.title': 'Configuración del Navegador',
    'cookies.management.browser.chrome': 'Chrome: Configuración → Privacidad y seguridad → Cookies y otros datos de sitios',
    'cookies.management.browser.firefox': 'Firefox: Opciones → Privacidad y seguridad → Cookies y datos del sitio',
    'cookies.management.browser.safari': 'Safari: Preferencias → Privacidad → Gestionar datos del sitio web',
    'cookies.management.browser.edge': 'Edge: Configuración → Cookies y permisos del sitio',
    'cookies.management.optout.title': 'Herramientas de Opt-out',
    'cookies.management.optout.item1': 'Google Analytics: Complemento de exclusión',
    'cookies.management.optout.item2': 'Configuración de cookies al ingresar al sitio',
    'cookies.management.optout.item3': 'Herramientas de privacidad del navegador',
    'cookies.management.note': 'Deshabilitar ciertas cookies puede afectar la funcionalidad del sitio web y su experiencia de navegación.',
    'cookies.thirdparty.title': 'Servicios de Terceros',
    'cookies.thirdparty.content1': 'Nuestro sitio web puede incluir servicios proporcionados por terceros que establecen sus propias cookies:',
    'cookies.thirdparty.google': 'Google Analytics: Para análisis de tráfico web y comportamiento de usuarios',
    'cookies.thirdparty.youtube': 'YouTube: Para reproducir videos corporativos embebidos',
    'cookies.thirdparty.maps': 'Google Maps: Para mostrar ubicaciones y facilitar navegación',
    'cookies.thirdparty.social': 'Redes Sociales: Botones de compartir y widgets de redes sociales',
    'cookies.thirdparty.content2': 'Cada servicio de terceros tiene sus propias políticas de cookies y privacidad. Le recomendamos revisar estas políticas para entender cómo manejan sus datos.',
    
    // Security Policy Content
    'security.commitment.title': 'Compromiso con la Seguridad',
    'security.commitment.content1': 'En TRANSERVICA, C.A., la seguridad no es solo una prioridad, es el fundamento de todas nuestras operaciones. Con 40 años de experiencia en transporte de cargas excepcionales, hemos desarrollado un sistema integral de gestión de seguridad que protege a nuestros empleados, clientes, comunidades y el medio ambiente.',
    'security.commitment.content2': 'Nuestro compromiso se basa en el principio de "Cero Accidentes" y el cumplimiento estricto de normativas nacionales e internacionales, manteniendo un récord de seguridad del 99.8% en más de 15,000 proyectos ejecutados.',
    'security.commitment.record.title': 'Nuestro Record de Seguridad',
    'security.commitment.record.safety': 'Índice de Seguridad',
    'security.commitment.record.projects': 'Proyectos Seguros',
    'security.commitment.record.experience': 'Años de Experiencia',
    'security.commitment.record.capacity': 'Tons. Capacidad Max.',
    'security.management.title': 'Sistema de Gestión de Seguridad',
    'security.management.content': 'Nuestro Sistema Integrado de Gestión (SIG) está certificado bajo las normas:',
    'security.management.iso45001': 'Sistemas de Gestión de Seguridad y Salud Ocupacional',
    'security.management.iso14001': 'Sistemas de Gestión Ambiental',
    'security.management.iso9001': 'Sistemas de Gestión de Calidad',
    'security.management.components.title': 'Componentes del Sistema',
    'security.management.components.item1': 'Identificación y evaluación continua de riesgos operacionales',
    'security.management.components.item2': 'Procedimientos de trabajo seguro para cada tipo de operación',
    'security.management.components.item3': 'Programas de capacitación y certificación del personal',
    'security.management.components.item4': 'Inspecciones regulares de equipos y herramientas',
    'security.management.components.item5': 'Auditorías internas y externas del sistema de gestión',
    'security.management.components.item6': 'Investigación y análisis de incidentes y casi-accidentes',
    'security.management.components.item7': 'Planes de respuesta ante emergencias y contingencias',
    'security.equipment.title': 'Seguridad de Equipos',
    'security.equipment.content': 'Nuestra flota de equipos especializados cumple con los más altos estándares de seguridad:',
    'security.equipment.trailers.title': 'Trailers Modulares Hidráulicos',
    'security.equipment.trailers.item1': 'Sistemas de control hidráulico con redundancia de seguridad',
    'security.equipment.trailers.item2': 'Monitoreo en tiempo real de presiones y temperaturas',
    'security.equipment.trailers.item3': 'Sistemas de frenado de emergencia automático',
    'security.equipment.trailers.item4': 'Configuraciones modulares adaptables a cada carga',
    'security.equipment.trailers.item5': 'Certificaciones CE y homologaciones internacionales',
    'security.equipment.cranes.title': 'Grúas y Equipos de Izamiento',
    'security.equipment.cranes.item1': 'Sistemas de control de cargas con limitadores automáticos',
    'security.equipment.cranes.item2': 'Dispositivos de seguridad anti-vuelco y estabilización',
    'security.equipment.cranes.item3': 'Mantenimiento preventivo según especificaciones del fabricante',
    'security.equipment.cranes.item4': 'Certificaciones anuales de capacidad y seguridad',
    'security.equipment.cranes.item5': 'Operadores certificados y especializados',
    'security.equipment.maintenance.title': 'Programa de Mantenimiento',
    'security.equipment.maintenance.item1': 'Inspecciones diarias antes de cada operación',
    'security.equipment.maintenance.item2': 'Mantenimiento preventivo cada 250, 500 y 1,000 horas',
    'security.equipment.maintenance.item3': 'Calibración periódica de sistemas de control',
    'security.equipment.maintenance.item4': 'Renovación de componentes críticos según especificaciones',
    'security.equipment.maintenance.item5': 'Registro digital completo de historial de mantenimiento'
  },
  en: {
    // Navigation
    'nav.home': 'HOME',
    'nav.services': 'SERVICES',
    'nav.projects': 'PROJECTS',
    'nav.company': 'COMPANY',
    'nav.contact': 'CONTACT',
    'nav.quote': 'QUOTE',
    'nav.blog': 'BLOG',
    
    // Hero Section
    'hero.title': 'Exceptional Heavy Cargo Transportation Venezuela - Up to 1,100 Tons',
    'hero.subtitle': '40+ Years Specialized in Heavy and Oversized Load Movement',
    'hero.description': 'Specialized in Heavy and Oversized Load Movement up to 1,100 tons with latest generation Hydraulic Modular trailers.',
    'hero.cta': 'REQUEST QUOTE',
    'hero.video': 'WATCH CORPORATE VIDEO',
    
    // Services Section
    'services.title': 'Specialized Transportation Services in Venezuela',
    'services.subtitle': 'Specialized solutions for exceptional cargo transportation',
    'services.transport.title': 'Exceptional Cargo Transportation',
    'services.transport.description': 'Mobilization of cargo up to 1,100 tons with state-of-the-art hydraulic modular trailers SCHEUERLE and COMETTO.',
    'services.transport.feature1': 'Up to 1,100 tons',
    'services.transport.feature2': 'Modular trailers',
    'services.transport.feature3': 'Specialized routes',
    'services.transport.feature4': 'Specialized escort',
    'services.cranes.title': 'Specialized Crane Lifting',
    'services.cranes.description': 'Lifting services with Mobile Telescopic and Crawler Cranes for complex industrial projects.',
    'services.cranes.feature1': 'Telescopic cranes',
    'services.cranes.feature2': 'Crawler cranes',
    'services.cranes.feature3': 'Precision lifting',
    'services.cranes.feature4': 'Certified operators',
    'services.logistics.title': 'Complete Engineering Logistics',
    'services.logistics.description': 'Comprehensive planning of transportation projects with feasibility studies and multimodal coordination.',
    'services.logistics.feature1': 'Feasibility studies',
    'services.logistics.feature2': 'Route planning',
    'services.logistics.feature3': 'Multimodal coordination',
    'services.logistics.feature4': 'Project management',
    'services.permits.title': 'INTT Permit Management',
    'services.permits.description': 'Complete permit processing with the National Institute of Land Transportation and competent authorities.',
    'services.permits.feature1': 'INTT permits',
    'services.permits.feature2': 'Complete documentation',
    'services.permits.feature3': 'Fast processing',
    'services.permits.feature4': 'Regulatory compliance',
    'services.feasibility.title': 'Technical Feasibility Studies',
    'services.feasibility.description': 'Detailed technical viability analysis to ensure the success of specialized transportation projects.',
    'services.feasibility.feature1': 'Route analysis',
    'services.feasibility.feature2': 'Structural evaluation',
    'services.feasibility.feature3': 'Load studies',
    'services.feasibility.feature4': 'Technical recommendations',
    'services.multimodal.title': 'Multimodal Coordination',
    'services.multimodal.description': 'Integrated land, sea and rail transportation services for international projects.',
    'services.multimodal.feature1': 'Land transportation',
    'services.multimodal.feature2': 'Maritime coordination',
    'services.multimodal.feature3': 'Rail transportation',
    'services.multimodal.feature4': 'International logistics',
    'services.consult': 'Consult',
    'services.quote': 'Quote',
    'services.cta.title': 'Need to Transport Exceptional Cargo?',
    'services.cta.subtitle': 'Let us Evaluate your Project and Offer you the Best Specialized Cargo Transportation Solution',
    'services.cta.quote': 'Request Quote Now',
    'services.cta.call': 'Speak with a Specialist',
    'services.cta': 'REQUEST INFORMATION',
    'services.watch': 'WATCH SERVICES',
    
    // About Section
    'about.title': 'ABOUT TRANSERVICA',
    'about.subtitle': '40 years transporting Venezuela\'s future',
    'about.description': 'We are a Venezuelan company specialized in exceptional cargo transportation with over 4 decades of experience. We feature German SCHEUERLE technology and a highly qualified team to handle the most challenging projects.',
    'about.experience': '40+ Years of Experience',
    'about.projects': '1000+ Successful Projects',
    'about.capacity': '1,100 Tons Capacity',
    'about.equipment': 'German Technology',
    'about.cta': 'LEARN MORE',
    'about.video': 'WATCH CORPORATE VIDEO',
    'about.benefit1.title': 'Exceptional capacity up to 1,100 tons',
    'about.benefit1.desc': 'Latest generation German hydraulic modular equipment.',
    'about.benefit2.title': 'National coverage with proven experience',
    'about.benefit2.desc': '40 years successfully transporting Venezuela\'s future.',
    'about.benefit3.title': 'Comprehensive platform with 24/7 support',
    'about.benefit3.desc': 'Complete tracking and specialists always available.',
    'about.benefit4.title': 'Personalized support with real humans',
    'about.benefit4.desc': 'Dedicated logistics specialists available at any time.',
    'about.mission.title': 'Mission',
    'about.mission.text': 'Providing mobilization and lifting services for oversized cargo through compliance with safety, guarantee and reliability criteria, anticipating and effectively responding to our clients\' needs, ensuring the welfare of our workers and maximizing productivity.',
    'about.vision.title': 'Vision',
    'about.vision.text': 'To be a nationally and internationally recognized company in the provision of mobilization and lifting services for oversized cargo, with qualified personnel, continuous improvement, opportunity utilization and permanent customer satisfaction.',
    'about.cta.title': 'Multiple Exceptional Loads. One Platform. Zero Complications.',
    'about.cta.subtitle': 'Compare heavy and oversized transportation quotes, book instantly and track in real time — all with TRANSERVICA.',
    'about.cta.quote': 'GET INSTANT QUOTE',
    'about.cta.call': 'SPEAK WITH A SPECIALIST',
    
    // Contact Section
    'contact.title': 'Request Your Quote',
    'contact.subtitle': 'Tell us about your project and we will provide you with a personalized solution with the best market proposal.',
    'contact.form.name': 'Name',
    'contact.form.name.placeholder': 'Your full name',
    'contact.form.email': 'Email',
    'contact.form.email.placeholder': 'your@email.com',
    'contact.form.phone': 'Phone',
    'contact.form.phone.placeholder': '+58 424 123 4567',
    'contact.form.company': 'Company',
    'contact.form.company.placeholder': 'Company name',
    'contact.form.cargo': 'Cargo Type',
    'contact.form.cargo.placeholder': 'Select type',
    'contact.form.cargo.industrial': 'Industrial Equipment',
    'contact.form.cargo.machinery': 'Heavy Machinery',
    'contact.form.cargo.turbines': 'Turbines',
    'contact.form.cargo.oil': 'Oil Equipment',
    'contact.form.cargo.naval': 'Naval Construction',
    'contact.form.cargo.others': 'Others',
    'contact.form.weight': 'Estimated Weight (Tons)',
    'contact.form.weight.placeholder': '100',
    'contact.form.origin': 'Origin',
    'contact.form.origin.placeholder': 'Origin city',
    'contact.form.destination': 'Destination',
    'contact.form.destination.placeholder': 'Destination city',
    'contact.form.description': 'Project Description',
    'contact.form.description.placeholder': 'Describe your project, dimensions, special features, required date, etc.',
    'contact.form.message': 'Message',
    'contact.form.submit': 'Request Free Quote',
    'contact.form.sending': 'Sending...',
    'contact.info.title': 'Contact Information',
    'contact.info.phones': 'Main Phones',
    'contact.info.email': 'Corporate Email',
    'contact.info.address': 'Address',
    'contact.address.full': 'National Highway Maracay Mariara Km 9, Mariara, Carabobo State',
    'hero.stats.years': '40',
    'hero.stats.years.title': 'Years of Experience',
    'hero.stats.years.subtitle': 'Leader in specialized transportation',
    'hero.stats.capacity': '1100',
    'hero.stats.capacity.title': 'Tons Capacity',
    'hero.stats.capacity.subtitle': 'Specialized technology',
    'hero.stats.reliability': '100%',
    'hero.stats.reliability.title': 'Reliability',
    'hero.stats.reliability.subtitle': 'Successful projects',
    'projects.title': 'Project Gallery',
    'projects.subtitle': 'Over 40 years transporting exceptional cargo up to 1,100 tons. Learn about some of our most outstanding projects carried out with specialized equipment and cutting-edge technology.',
    'equipment.title': 'Our Specialized Equipment for Lifting and Transportation of Exceptional and Oversized Cargo',
    'equipment.subtitle': 'Specialized technology for transportation with German equipment',
    'equipment.cta.title': 'Need Specialized Equipment for Your Project?',
    'equipment.cta.subtitle': 'We have Venezuela\'s most modern fleet for exceptional cargo transportation',
    'equipment.cta.button': 'REQUEST QUOTE',
    
    // FAQ Section
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Solve your doubts about our specialized transportation services',
    'faq.q1': 'What is the maximum load capacity you can transport?',
    'faq.a1': 'Our specialized fleet can transport up to 1,100 tons using state-of-the-art hydraulic modular trailers.',
    'faq.q2': 'What type of permits do I need for my cargo?',
    'faq.a2': 'We handle all the management of special permits, documentation and coordination with competent authorities.',
    'faq.q3': 'Do you cover the entire Venezuelan territory?',
    'faq.a3': 'Yes, we offer specialized transportation services throughout the national territory with optimized routes and comprehensive logistics.',
    'faq.q4': 'What does the transportation service include?',
    'faq.a4': 'It includes route planning, permits, insurance, loading/unloading, specialized escort and real-time monitoring.',
    
    // Equipment items
    'equipment.item1.name': 'Hydraulic modular combinations for loads up to 1,100 tons',
    'equipment.item1.description': 'Specialized technology for exceptional cargo transportation',
    'equipment.item1.capacity': '1,100 tons',
    'equipment.item1.feature1': 'Advanced hydraulic systems',
    'equipment.item1.feature2': 'Modular configuration',
    'equipment.item1.feature3': 'Digital systems',
    'equipment.item1.feature4': 'Adaptive suspension',
    'equipment.item2.name': 'Specialized Systems up to 1100 tons',
    'equipment.item2.description': 'Self-propelled high-precision platforms for critical loads',
    'equipment.item2.capacity': 'up to 1100 tons',
    'equipment.item2.feature1': 'Self-propelled',
    'equipment.item2.feature2': 'Precision control',
    'equipment.item2.feature3': 'Navigation systems',
    'equipment.item2.feature4': 'Remote operation',
    'equipment.item3.name': 'Telescopic Mobile Cranes up to 500 tons',
    'equipment.item3.description': 'High Capacity Mobile Cranes for Specialized Lifting Operations',
    'equipment.item3.capacity': 'up to 500 tons',
    'equipment.item3.feature1': 'High mobility',
    'equipment.item3.feature2': 'Digital controls',
    'equipment.item3.feature3': 'Certified operators',
    'equipment.item4.name': 'Crawler Cranes up to 800 tons',
    'equipment.item4.description': 'Specialized Equipment for Lifting in Difficult Terrain',
    'equipment.item4.capacity': 'up to 800 tons',
    'equipment.item4.feature1': 'Crawler base',
    'equipment.item4.feature2': 'Superior stability',
    'equipment.item4.feature3': 'Extended reach',
    'equipment.item4.feature4': 'Versatile configuration',
    'equipment.item5.name': 'Specialized Trucks Variable',
    'equipment.item5.description': 'Specialized Truck Fleet Rental for Different Types of Cargo',
    'equipment.item5.capacity': 'Variable',
    'equipment.item5.feature1': 'High power',
    'equipment.item5.feature2': 'Specialized transmission',
    'equipment.item5.feature3': 'Safety systems',
    'equipment.item5.feature4': 'Preventive maintenance',
    'equipment.item6.name': 'Support Equipment Various',
    'equipment.item6.description': 'Complementary systems for complex transportation operations',
    'equipment.item6.capacity': 'Various',
    'equipment.item6.feature1': 'Support systems',
    'equipment.item6.feature2': 'Auxiliary equipment',
    'equipment.item6.feature3': 'Specialized tools',
    'equipment.item6.feature4': 'Technical support',
    'equipment.specs.button': 'View Specifications',
    'projects.1.title': 'Metro Caracas Railway Transport',
    'projects.1.weight': '280 tons',
    'projects.1.sector': 'Railway Transport',
    'projects.1.location': 'Puerto La Guaira - Caracas',
    'projects.1.description': 'Specialized transport of Metro Caracas wagons with hydraulic modular trailers',
    'projects.2.title': 'Protected Railway Equipment',
    'projects.2.weight': '250 tons',
    'projects.2.sector': 'Railway Transport',
    'projects.2.location': 'Puerto Cabello - Interior',
    'projects.2.description': 'Metro wagons with special protection during land transport',
    'projects.3.title': 'Multicar Railway Convoy',
    'projects.3.weight': '450 tons',
    'projects.3.sector': 'Railway Transport',
    'projects.3.location': 'National Operation',
    'projects.3.description': 'Multiple wagons transported simultaneously with comprehensive logistical coordination',
    'projects.4.title': 'Specialized Road Transport',
    'projects.4.weight': '380 tons',
    'projects.4.sector': 'Industrial Logistics',
    'projects.4.location': 'National Routes',
    'projects.4.description': 'Exceptional cargo transport convoy on Venezuelan highways',
    
    // Project CTA buttons
    'projects.cta.1': 'QUOTE SIMILAR PROJECT',
    'projects.cta.2': 'VIEW MORE PROJECTS',
    'projects.cta.3': 'REQUEST INFORMATION',
    'projects.cta.4': 'CONTACT SPECIALIST',
    'projects.cta.5': 'KNOW CAPABILITIES',
    'projects.cta.6': 'EVALUATE MY CARGO',
    'projects.cta.7': 'PLAN TRANSPORT',
    'projects.cta.8': 'CHECK AVAILABILITY',
    'projects.cta.9': 'GET BUDGET',
    'projects.cta.10': 'FREE TECHNICAL ADVICE',
    'projects.cta.11': 'FEASIBILITY STUDIES',
    'projects.cta.12': 'LOGISTICS COORDINATION',
    
    // Project stats
    'projects.stats.of': 'of',
    'projects.stats.projects': 'projects',
    'projects.stats.years': 'years experience',
    
    // Footer
    'footer.description': 'Specialized in exceptional cargo transportation up to 1,100 tons with hydraulic modular trailers. 40 years transporting Venezuela\'s future with cutting-edge German technology.',
    
    // Footer sections
    'footer.pages.title': 'Pages',
    'footer.pages.home': 'Home',
    'footer.pages.about': 'About',
    'footer.pages.services': 'Services',
    'footer.pages.projects': 'Projects',
    'footer.pages.contact': 'Contact',
    
    'footer.resources.title': 'Resources',
    'footer.resources.blog': 'Blog',
    'footer.resources.equipment': 'Equipment',
    'footer.resources.help': 'Help Center',
    'footer.resources.specifications': 'Specifications',
    'footer.resources.testimonials': 'Testimonials',
    
    'footer.policies.privacy': 'Data Protection Policy',
    'footer.policies.security': 'Comprehensive Road Safety Policy',
    'footer.policies.management': 'Integrated Management Policy',
    
    'footer.legal.terms': 'Terms of Service',
    'footer.legal.privacy': 'Privacy Policy',
    'footer.legal.cookies': 'Cookie Agreement',
    'footer.legal.security': 'Security Policy',
    
    'footer.social.title': 'Follow us on',
    'footer.quote.button': 'REQUEST QUOTE',
    'footer.maps.button': 'VIEW ON GOOGLE MAPS',
    'footer.services.title': 'Services',
    'footer.services.transport': 'Specialized Transportation',
    'footer.services.engineering': 'Engineering Logistics',
    'footer.services.hydraulic': 'Hydraulic Modular',
    'footer.services.cranes': 'Grove and Liebherr Cranes',
    'footer.resources.about': 'About Us',
    'footer.resources.docs': 'Technical Documentation',
    'footer.resources.faq': 'FAQs',
    'footer.newsletter.title': 'Subscribe to our newsletter',
    'footer.newsletter.placeholder': 'Work Email',
    'footer.newsletter.subscribe': 'Subscribe',
    'footer.copyright': '© 2024 TRANSERVICA, C.A. All rights reserved.',
    'footer.rif': 'RIF: J-00207776-0 | 40 years transporting Venezuela\'s future',
    'footer.follow': 'FOLLOW ON SOCIAL',
    
    // Language Switcher
    'language.spanish': 'ESPAÑOL',
    'language.english': 'ENGLISH',
    
    // Blog
    'blog.title': 'TRANSERVICA BLOG',
    'blog.subtitle': 'News and specialized transportation projects',
    'blog.readMore': 'READ MORE',
    'blog.backToHome': 'BACK TO HOME',
    'blog.section.badge': 'Corporate Blog',
    'blog.section.title': 'TRANSERVICA NEWS',
    'blog.section.description': 'News and Specialized Cargo Transportation Projects',
    'blog.section.featured': 'Featured News and Projects',
    'blog.section.readFullArticle': 'Read Full Article',
    'blog.section.newsletter.title': 'TRANSERVICA Newsletter',
    'blog.section.newsletter.description': 'Receive exclusive news about specialized transportation projects, cutting-edge equipment and industry regulations',
    'blog.section.newsletter.placeholder': 'Enter your corporate email',
    'blog.section.newsletter.subscribe': 'Subscribe to Blog',
    'blog.section.viewAll': 'View All Blog Articles',
    'blog.section.cta.title': 'Do You Have a Specialized Project?',
    'blog.section.cta.description': '40 years of experience back us up. Our team of engineers is ready to develop the best logistics solution for your company',
    'blog.section.cta.consult': 'Consult Project',
    'blog.section.cta.services': 'View Services',
    
    // Legal Pages
    'legal.terms.title': 'Terms of Service',
    'legal.terms.description': 'General conditions governing specialized transportation services of TRANSERVICA, C.A.',
    'legal.privacy.title': 'Privacy Policy',
    'legal.privacy.description': 'Protection and treatment of personal data at TRANSERVICA, C.A.',
    'legal.cookies.title': 'Cookie Agreement',
    'legal.cookies.description': 'Information about the use of cookies and similar technologies on our website',
    'legal.security.title': 'Security Policy',
    'legal.security.description': 'Comprehensive commitment to safety in exceptional cargo transportation',
    
    // Terms of Service Content
    'terms.acceptance.title': 'Terms Acceptance',
    'terms.acceptance.content1': 'By contracting the services of TRANSERVICA, C.A. (hereinafter "the Company"), the client expressly accepts these terms and conditions. These terms constitute a legally binding agreement between the client and TRANSERVICA, C.A., a company specialized in exceptional cargo transportation with 40 years of experience.',
    'terms.acceptance.content2': 'The use of our services implies total and unconditional acceptance of these conditions, which will prevail over any other condition established by the client.',
    'terms.services.title': 'Service Description',
    'terms.services.content1': 'TRANSERVICA, C.A. offers specialized services for exceptional cargo transportation up to 1,100 tons, using latest generation SCHEUERLE and COMETTO hydraulic modular trailers. Our services include:',
    'terms.services.item1': 'Exceptional and oversized cargo transportation',
    'terms.services.item2': 'Mobile and crawler crane services up to 800 tons',
    'terms.services.item3': 'Comprehensive logistics and special project coordination',
    'terms.services.item4': 'Feasibility studies and route planning',
    'terms.services.item5': 'Specialized lifting and assembly services',
    'terms.services.content2': 'All services are executed under strict safety protocols and complying with applicable Venezuelan and international regulations.',
    'terms.responsibilities.title': 'Client Responsibilities',
    'terms.responsibilities.content1': 'The client agrees to:',
    'terms.responsibilities.item1': 'Provide accurate and complete information about cargo characteristics',
    'terms.responsibilities.item2': 'Obtain all necessary permits and authorizations when required',
    'terms.responsibilities.item3': 'Facilitate access to loading and unloading points under agreed conditions',
    'terms.responsibilities.item4': 'Pay for services according to established commercial conditions',
    'terms.responsibilities.item5': 'Comply with safety standards and protocols established by TRANSERVICA',
    'terms.responsibilities.content2': 'Non-compliance with these obligations may result in service suspension and billing of additional costs.',
    'terms.limitations.title': 'Liability Limitations',
    'terms.limitations.content1': 'TRANSERVICA, C.A. maintains insurance policies that cover the services provided according to the terms and limits established therein. The company\'s liability is limited to:',
    'terms.limitations.item1': 'Damages caused by proven negligence in service provision',
    'terms.limitations.item2': 'Limits established in current insurance policies',
    'terms.limitations.item3': 'Exclusion of lost profits, indirect or consequential damages',
    'terms.limitations.content2': 'No responsibility is accepted for delays caused by external factors such as weather conditions, government restrictions, or force majeure circumstances.',
    'terms.payment.title': 'Payment Terms',
    'terms.payment.content1': 'Services are billed according to current rates at the time of service provision. Payment conditions include:',
    'terms.payment.item1': '50% advance payment upon service confirmation',
    'terms.payment.item2': 'Remaining balance upon delivery or according to agreed terms',
    'terms.payment.item3': 'Billing of additional services not included in the original quote',
    'terms.payment.item4': 'Late payment penalties according to commercial conditions',
    'terms.forceMajeure.title': 'Force Majeure',
    'terms.forceMajeure.content': 'TRANSERVICA, C.A. will not be responsible for non-compliance with its obligations when this is due to force majeure causes, including but not limited to: natural disasters, labor conflicts, government restrictions, pandemics, or any other circumstance beyond the reasonable control of the company.',
    'terms.modifications.title': 'Modifications',
    'terms.modifications.content': 'TRANSERVICA, C.A. reserves the right to modify these terms and conditions at any time. Modifications will take effect immediately after their publication on the company\'s official website. It is recommended to periodically review these terms.',
    'terms.contact.title': 'Contact Information',
    
    // Privacy Policy Content
    'privacy.introduction.title': 'Introduction',
    'privacy.introduction.content1': 'TRANSERVICA, C.A., a company specialized in exceptional cargo transportation, recognizes the importance of protecting the privacy and personal data of our clients, suppliers, employees and visitors to our website.',
    'privacy.introduction.content2': 'This Privacy Policy establishes how we collect, use, store and protect the personal information you provide to us, in compliance with applicable Venezuelan laws and international best practices.',
    'privacy.collection.title': 'Information Collection',
    'privacy.collection.content1': 'We collect personal information in the following ways:',
    'privacy.collection.direct.title': 'Direct Information',
    'privacy.collection.direct.item1': 'Data provided in contact and quotation forms',
    'privacy.collection.direct.item2': 'Commercial information for service provision',
    'privacy.collection.direct.item3': 'Employee and collaborator data',
    'privacy.collection.direct.item4': 'Records of telephone and email communications',
    'privacy.collection.automatic.title': 'Automatic Information',
    'privacy.collection.automatic.item1': 'IP address and browsing data on our website',
    'privacy.collection.automatic.item2': 'Cookies and similar technologies',
    'privacy.collection.automatic.item3': 'Device information and browsing preferences',
    'privacy.collection.automatic.item4': 'Website access and usage logs',
    'privacy.usage.title': 'Information Use',
    'privacy.usage.content1': 'We use the collected information for the following purposes:',
    'privacy.usage.item1': 'Provision of specialized transportation services',
    'privacy.usage.item2': 'Communication with clients and project monitoring',
    'privacy.usage.item3': 'Quote processing and billing',
    'privacy.usage.item4': 'Improvement of our services and user experience',
    'privacy.usage.item5': 'Compliance with legal and regulatory obligations',
    'privacy.usage.item6': 'Direct marketing and commercial communications (with consent)',
    'privacy.usage.item7': 'Statistical analysis and internal market studies',
    'privacy.usage.content2': 'We do not use personal information for purposes other than those mentioned without obtaining express consent from the data subject.',
    'privacy.protection.title': 'Data Protection',
    'privacy.protection.content1': 'TRANSERVICA implements appropriate technical and organizational measures to protect personal data against:',
    'privacy.protection.item1': 'Unauthorized access, alteration, disclosure or destruction',
    'privacy.protection.item2': 'Accidental loss or unlawful processing',
    'privacy.protection.item3': 'Unauthorized transfers',
    'privacy.protection.security.title': 'Security Measures',
    'privacy.protection.security.item1': 'Encryption of sensitive data in transit and storage',
    'privacy.protection.security.item2': 'Role-based access control and need-to-know basis',
    'privacy.protection.security.item3': 'Continuous system monitoring and anomaly detection',
    'privacy.protection.security.item4': 'Regular staff training in data protection',
    'privacy.protection.security.item5': 'Secure backup and business continuity plans',
    'privacy.sharing.title': 'Information Sharing',
    'privacy.sharing.content1': 'TRANSERVICA does not sell, rent or share personal information with third parties, except in the following circumstances:',
    'privacy.sharing.item1': 'With service providers who require the information to complete projects',
    'privacy.sharing.item2': 'When required by competent legal authorities',
    'privacy.sharing.item3': 'To protect the rights, property or safety of the company',
    'privacy.sharing.item4': 'With explicit consent of the data subject',
    'privacy.sharing.item5': 'In case of merger, acquisition or transfer of business assets',
    'privacy.sharing.content2': 'Any third party accessing personal information must commit to maintaining the same level of protection established in this policy.',
    'privacy.rights.title': 'Data Subject Rights',
    'privacy.rights.content1': 'You have the right to:',
    'privacy.rights.item1': 'Access your personal data that we maintain',
    'privacy.rights.item2': 'Rectify inaccurate or incomplete information',
    'privacy.rights.item3': 'Request deletion of your personal data',
    'privacy.rights.item4': 'Object to processing of your data for direct marketing',
    'privacy.rights.item5': 'Request portability of your data',
    'privacy.rights.item6': 'File complaints with data protection authorities',
    'privacy.rights.content2': 'To exercise these rights, you can contact us through the means provided at the end of this policy.',
    'privacy.retention.title': 'Data Retention',
    'privacy.retention.content1': 'We retain personal data for the time necessary to fulfill the purposes established in this policy, considering:',
    'privacy.retention.item1': 'Duration of the commercial or contractual relationship',
    'privacy.retention.item2': 'Legal obligations for record retention',
    'privacy.retention.item3': 'Legal defense needs and dispute resolution',
    'privacy.retention.item4': 'Statistical or archival purposes of public interest',
    'privacy.updates.title': 'Updates',
    'privacy.updates.content': 'This Privacy Policy may be updated periodically to reflect changes in our practices, services or legal requirements. Significant modifications will be notified through our website and other appropriate means.',
    'privacy.contact.title': 'Contact for Privacy Matters',
    
    // Cookies Policy Content
    'cookies.what.title': 'What are Cookies?',
    'cookies.what.content1': 'Cookies are small text files that are stored on your device when you visit our website. These technologies allow us to recognize your browser and device, remember your preferences and improve your browsing experience.',
    'cookies.what.content2': 'TRANSERVICA, C.A. uses cookies to provide an optimized web experience, analyze site usage and personalize content according to the needs of our visitors.',
    'cookies.types.title': 'Types of Cookies We Use',
    'cookies.types.essential.title': 'Essential Cookies',
    'cookies.types.essential.content': 'These cookies are necessary for the basic functioning of the website and cannot be disabled. They include:',
    'cookies.types.essential.item1': 'Session cookies to maintain functionality during your visit',
    'cookies.types.essential.item2': 'Security cookies to protect against malicious attacks',
    'cookies.types.essential.item3': 'Language preference and regional configuration cookies',
    'cookies.types.essential.item4': 'Form cookies to remember entered information',
    'cookies.types.analytics.title': 'Analytics Cookies',
    'cookies.types.analytics.content': 'They help us understand how visitors interact with our website:',
    'cookies.types.analytics.item1': 'Google Analytics for traffic and behavior analysis',
    'cookies.types.analytics.item2': 'Tracking of pages visited and time spent',
    'cookies.types.analytics.item3': 'Identification of most popular and relevant content',
    'cookies.types.analytics.item4': 'Analysis of navigation routes and exit points',
    'cookies.types.functional.title': 'Functional Cookies',
    'cookies.types.functional.content': 'They improve site functionality and personalization:',
    'cookies.types.functional.item1': 'Remember language and region preferences',
    'cookies.types.functional.item2': 'Maintain accessibility settings',
    'cookies.types.functional.item3': 'Personalize content based on previous interactions',
    'cookies.types.functional.item4': 'Facilitate the use of contact forms',
    'cookies.management.title': 'Cookie Management',
    'cookies.management.content': 'You have full control over the cookies used on our website. You can manage your preferences in the following ways:',
    'cookies.management.browser.title': 'Browser Settings',
    'cookies.management.browser.chrome': 'Chrome: Settings → Privacy and security → Cookies and other site data',
    'cookies.management.browser.firefox': 'Firefox: Options → Privacy and security → Cookies and site data',
    'cookies.management.browser.safari': 'Safari: Preferences → Privacy → Manage website data',
    'cookies.management.browser.edge': 'Edge: Settings → Cookies and site permissions',
    'cookies.management.optout.title': 'Opt-out Tools',
    'cookies.management.optout.item1': 'Google Analytics: Opt-out browser add-on',
    'cookies.management.optout.item2': 'Cookie settings when entering the site',
    'cookies.management.optout.item3': 'Browser privacy tools',
    'cookies.management.note': 'Disabling certain cookies may affect website functionality and your browsing experience.',
    'cookies.thirdparty.title': 'Third Party Services',
    'cookies.thirdparty.content1': 'Our website may include services provided by third parties that set their own cookies:',
    'cookies.thirdparty.google': 'Google Analytics: For web traffic analysis and user behavior',
    'cookies.thirdparty.youtube': 'YouTube: For playing embedded corporate videos',
    'cookies.thirdparty.maps': 'Google Maps: To show locations and facilitate navigation',
    'cookies.thirdparty.social': 'Social Networks: Share buttons and social media widgets',
    'cookies.thirdparty.content2': 'Each third-party service has its own cookie and privacy policies. We recommend reviewing these policies to understand how they handle your data.',
    
    // Security Policy Content
    'security.commitment.title': 'Commitment to Safety',
    'security.commitment.content1': 'At TRANSERVICA, C.A., safety is not just a priority, it is the foundation of all our operations. With 40 years of experience in exceptional cargo transportation, we have developed a comprehensive safety management system that protects our employees, clients, communities and the environment.',
    'security.commitment.content2': 'Our commitment is based on the "Zero Accidents" principle and strict compliance with national and international regulations, maintaining a safety record of 99.8% in more than 15,000 executed projects.',
    'security.commitment.record.title': 'Our Safety Record',
    'security.commitment.record.safety': 'Safety Index',
    'security.commitment.record.projects': 'Safe Projects',
    'security.commitment.record.experience': 'Years of Experience',
    'security.commitment.record.capacity': 'Max. Capacity Tons',
    'security.management.title': 'Safety Management System',
    'security.management.content': 'Our Integrated Management System (IMS) is certified under the standards:',
    'security.management.iso45001': 'Occupational Health and Safety Management Systems',
    'security.management.iso14001': 'Environmental Management Systems',
    'security.management.iso9001': 'Quality Management Systems',
    'security.management.components.title': 'System Components',
    'security.management.components.item1': 'Continuous identification and evaluation of operational risks',
    'security.management.components.item2': 'Safe work procedures for each type of operation',
    'security.management.components.item3': 'Personnel training and certification programs',
    'security.management.components.item4': 'Regular equipment and tool inspections',
    'security.management.components.item5': 'Internal and external management system audits',
    'security.management.components.item6': 'Investigation and analysis of incidents and near-misses',
    'security.management.components.item7': 'Emergency and contingency response plans',
    'security.equipment.title': 'Equipment Safety',
    'security.equipment.content': 'Our specialized equipment fleet meets the highest safety standards:',
    'security.equipment.trailers.title': 'Hydraulic Modular Trailers',
    'security.equipment.trailers.item1': 'Hydraulic control systems with safety redundancy',
    'security.equipment.trailers.item2': 'Real-time monitoring of pressures and temperatures',
    'security.equipment.trailers.item3': 'Automatic emergency braking systems',
    'security.equipment.trailers.item4': 'Modular configurations adaptable to each load',
    'security.equipment.trailers.item5': 'CE certifications and international approvals',
    'security.equipment.cranes.title': 'Cranes and Lifting Equipment',
    'security.equipment.cranes.item1': 'Load control systems with automatic limiters',
    'security.equipment.cranes.item2': 'Anti-tip and stabilization safety devices',
    'security.equipment.cranes.item3': 'Preventive maintenance according to manufacturer specifications',
    'security.equipment.cranes.item4': 'Annual capacity and safety certifications',
    'security.equipment.cranes.item5': 'Certified and specialized operators',
    'security.equipment.maintenance.title': 'Maintenance Program',
    'security.equipment.maintenance.item1': 'Daily inspections before each operation',
    'security.equipment.maintenance.item2': 'Preventive maintenance every 250, 500 and 1,000 hours',
    'security.equipment.maintenance.item3': 'Periodic calibration of control systems',
    'security.equipment.maintenance.item4': 'Renewal of critical components according to specifications',
    'security.equipment.maintenance.item5': 'Complete digital record of maintenance history'
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('es');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['es']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}