import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation object
const translations = {
  es: {
    // Navigation
    'nav.home': 'HOME',
    'nav.services': 'SERVICIOS',
    'nav.projects': 'PROYECTOS',
    'nav.company': 'COMPAÑÍA',
    'nav.contact': 'CONTACTO',
    'nav.quote': 'COTIZAR',
    'nav.blog': 'BLOG',
    
    // Hero Section
    'hero.title': 'Transporte Cargas Excepcionales Venezuela - Especializados en Movilización de Cargas Pesada y Sobredimensionada',
    'hero.subtitle': 'CON 40 AÑOS TRANSPORTANDO EL FUTURO DE VENEZUELA',
    'hero.description': 'Especializados en Movilización de Cargas Pesadas y Sobredimensionadas hasta 1,100 toneladas con trailers Modulares Hidráulicos de última generación.',
    'hero.cta': 'SOLICITAR COTIZACIÓN',
    'hero.video': 'VER VIDEO CORPORATIVO',
    
    // Services Section
    'services.title': 'NUESTROS SERVICIOS',
    'services.subtitle': 'Soluciones especializadas en transporte de cargas excepcionales',
    'services.transport.title': 'Transporte de Cargas Excepcionales',
    'services.transport.description': 'Movilización de cargas hasta 1,100 toneladas con trailers modulares hidráulicos SCHEUERLE y COMETTO de última generación.',
    'services.transport.feature1': 'Hasta 1,100 toneladas',
    'services.transport.feature2': 'Trailers modulares',
    'services.transport.feature3': 'Rutas especializadas',
    'services.transport.feature4': 'Escolta especializada',
    'services.cranes.title': 'Izamiento con Grúas Especializadas',
    'services.cranes.description': 'Servicios de izamiento con Grúas Móviles Telescópicas y Sobre Orugas para proyectos industriales complejos.',
    'services.cranes.feature1': 'Grúas telescópicas',
    'services.cranes.feature2': 'Grúas sobre orugas',
    'services.cranes.feature3': 'Izamiento preciso',
    'services.cranes.feature4': 'Operadores certificados',
    'services.logistics.title': 'Logística de Ingeniería Completa',
    'services.logistics.description': 'Planificación integral de proyectos de transporte con estudios de factibilidad y coordinación multimodal.',
    'services.logistics.feature1': 'Estudios de factibilidad',
    'services.logistics.feature2': 'Planificación de rutas',
    'services.logistics.feature3': 'Coordinación multimodal',
    'services.logistics.feature4': 'Gestión de proyecto',
    'services.permits.title': 'Gestión de Permisos INTT',
    'services.permits.description': 'Tramitación completa de permisos ante el Instituto Nacional de Transporte Terrestre y autoridades competentes.',
    'services.permits.feature1': 'Permisos INTT',
    'services.permits.feature2': 'Documentación completa',
    'services.permits.feature3': 'Gestión rápida',
    'services.permits.feature4': 'Cumplimiento normativo',
    'services.feasibility.title': 'Estudios de Factibilidad Técnica',
    'services.feasibility.description': 'Análisis detallado de viabilidad técnica para garantizar el éxito de proyectos de transporte especializado.',
    'services.feasibility.feature1': 'Análisis de rutas',
    'services.feasibility.feature2': 'Evaluación estructural',
    'services.feasibility.feature3': 'Estudios de carga',
    'services.feasibility.feature4': 'Recomendaciones técnicas',
    'services.multimodal.title': 'Coordinación Multimodal',
    'services.multimodal.description': 'Servicios integrados de transporte terrestre, marítimo y ferroviario para proyectos internacionales.',
    'services.multimodal.feature1': 'Transporte terrestre',
    'services.multimodal.feature2': 'Coordinación marítima',
    'services.multimodal.feature3': 'Transporte ferroviario',
    'services.multimodal.feature4': 'Logística internacional',
    'services.consult': 'Consultar',
    'services.quote': 'Cotizar',
    'services.cta.title': '¿Necesita Transportar Cargas Excepcionales?',
    'services.cta.subtitle': 'Permítanos Evaluar su Proyecto y Ofrecerle la Mejor Solución de Transporte de Carga Especializado',
    'services.cta.quote': 'Solicitar Cotización Ahora',
    'services.cta.call': 'Hablar con un Especialista',
    'services.cta': 'SOLICITAR INFORMACIÓN',
    'services.watch': 'VER SERVICIOS',
    
    // About Section
    'about.title': 'SOBRE TRANSERVICA',
    'about.subtitle': '40 años transportando el futuro de Venezuela',
    'about.description': 'Somos una empresa venezolana especializada en transporte de cargas excepcionales con más de 4 décadas de experiencia. Contamos con tecnología alemana SCHEUERLE y un equipo altamente calificado para manejar los proyectos más desafiantes.',
    'about.experience': '40+ Años de Experiencia',
    'about.projects': '1000+ Proyectos Exitosos',
    'about.capacity': '1,100 Toneladas Capacidad',
    'about.equipment': 'Tecnología Alemana',
    'about.cta': 'CONOCER MÁS',
    'about.video': 'VER VIDEO CORPORATIVO',
    'about.benefit1.title': 'Capacidad excepcional hasta 1,100 toneladas',
    'about.benefit1.desc': 'Equipos modulares hidráulicos alemanes de última generación.',
    'about.benefit2.title': 'Cobertura nacional con experiencia comprobada',
    'about.benefit2.desc': '40 años transportando el futuro de Venezuela con éxito.',
    'about.benefit3.title': 'Plataforma integral con soporte 24/7',
    'about.benefit3.desc': 'Seguimiento completo y especialistas disponibles siempre.',
    'about.benefit4.title': 'Soporte personalizado con humanos reales',
    'about.benefit4.desc': 'Especialistas en logística dedicados disponibles en cualquier momento.',
    'about.mission.title': 'Misión',
    'about.mission.text': 'Prestación del servicio de movilización e izamiento de cargas sobredimensionadas mediante el cumplimiento de criterios de seguridad, garantía y confiabilidad, anticipando y respondiendo eficazmente las necesidades de nuestros clientes, procurando el bienestar de nuestros trabajadores y maximizando la productividad.',
    'about.vision.title': 'Visión',
    'about.vision.text': 'Ser una empresa reconocida nacional e internacionalmente en la prestación de servicios de movilización e izamiento de cargas sobredimensionadas, con personal calificado, mejoramiento continuo, aprovechamiento de oportunidades y satisfacción permanente de clientes.',
    'about.cta.title': 'Múltiples Cargas Excepcionales. Una Plataforma. Cero Complicaciones.',
    'about.cta.subtitle': 'Compare cotizaciones de transporte pesado y sobredimensionado, reserve al instante y rastree en tiempo real — todo con TRANSERVICA.',
    'about.cta.quote': 'OBTENER COTIZACIÓN INSTANTÁNEA',
    'about.cta.call': 'HABLAR CON UN ESPECIALISTA',
    
    // Contact Section
    'contact.title': 'Solicita tu Cotización',
    'contact.subtitle': 'Cuéntanos sobre tu proyecto y te proporcionaremos una solución personalizada con la mejor propuesta del mercado.',
    'contact.form.name': 'Nombre',
    'contact.form.name.placeholder': 'Tu nombre completo',
    'contact.form.email': 'Email',
    'contact.form.email.placeholder': 'tu@email.com',
    'contact.form.phone': 'Teléfono',
    'contact.form.phone.placeholder': '+58 424 123 4567',
    'contact.form.company': 'Empresa',
    'contact.form.company.placeholder': 'Nombre de la empresa',
    'contact.form.cargo': 'Tipo de Carga',
    'contact.form.cargo.placeholder': 'Seleccionar tipo',
    'contact.form.cargo.industrial': 'Equipos Industriales',
    'contact.form.cargo.machinery': 'Maquinaria Pesada',
    'contact.form.cargo.turbines': 'Turbinas',
    'contact.form.cargo.oil': 'Equipos Petroleros',
    'contact.form.cargo.naval': 'Construcción Naval',
    'contact.form.cargo.others': 'Otros',
    'contact.form.weight': 'Peso Estimado (Toneladas)',
    'contact.form.weight.placeholder': '100',
    'contact.form.origin': 'Origen',
    'contact.form.origin.placeholder': 'Ciudad de origen',
    'contact.form.destination': 'Destino',
    'contact.form.destination.placeholder': 'Ciudad de destino',
    'contact.form.description': 'Descripción del Proyecto',
    'contact.form.description.placeholder': 'Describe tu proyecto, dimensiones, características especiales, fecha requerida, etc.',
    'contact.form.message': 'Mensaje',
    'contact.form.submit': 'Solicitar Cotización Gratuita',
    'contact.form.sending': 'Enviando...',
    'contact.info.title': 'Información de Contacto',
    'contact.info.phones': 'Teléfonos Principales',
    'contact.info.email': 'Dirección Comercial',
    'contact.info.executive': 'Dirección Ejecutiva',
    // Hero Stats - Critical for translation
    'hero.stats.years': '40',
    'hero.stats.years.title': 'Años de Experiencia',
    'hero.stats.years.subtitle': 'Líder en transporte especializado',
    'hero.stats.capacity': '1100',
    'hero.stats.capacity.title': 'Toneladas de Capacidad',
    'hero.stats.capacity.subtitle': 'Equipos de última generación',
    'hero.stats.reliability': '100%',
    'hero.stats.reliability.title': 'Confiabilidad',
    'hero.stats.reliability.subtitle': 'Proyectos exitosos',
    // Projects Gallery  
    'projects.title': 'Galería de Proyectos',
    'projects.subtitle': 'Más de 40 años transportando cargas excepcionales hasta 1,100 toneladas. Conoce algunos de nuestros proyectos más destacados realizados con equipos especializados y tecnología de vanguardia.',
    'equipment.title': 'Nuestros Equipos Especializados para Izamiento y Transportes de Carga Excepcionales y Sobredimensionadas',
    'equipment.subtitle': 'Equipos de última generación para transporte especializado con tecnología alemana',
    'equipment.cta.title': '¿Necesita Equipos Especializados para su Proyecto?',
    'equipment.cta.subtitle': 'Contamos con la flota más moderna de Venezuela para transporte de cargas excepcionales',
    'equipment.cta.button': 'SOLICITAR COTIZACIÓN',
    
    // FAQ Section
    'faq.title': 'Preguntas Frecuentes',
    'faq.subtitle': 'Resuelve tus dudas sobre nuestros servicios de transporte especializado',
    'faq.q1': '¿Cuál es la capacidad máxima de carga que pueden transportar?',
    'faq.a1': 'Nuestra flota especializada puede transportar hasta 1,100 toneladas utilizando remolques modulares hidráulicos de última generación.',
    'faq.q2': '¿Qué tipo de permisos necesito para mi carga?',
    'faq.a2': 'Nosotros nos encargamos de toda la gestión de permisos especiales, documentación y coordinación con autoridades competentes.',
    'faq.q3': '¿Cubren todo el territorio venezolano?',
    'faq.a3': 'Sí, ofrecemos servicios de transporte especializado en todo el territorio nacional con rutas optimizadas y logística integral.',
    'faq.q4': '¿Qué incluye el servicio de transporte?',
    'faq.a4': 'Incluye planificación de ruta, permisos, seguros, carga/descarga, escolta especializada y monitoreo en tiempo real.',
    
    // Equipment items
    'equipment.item1.name': 'Trailers Modulares Hidráulicos 1,100 toneladas',
    'equipment.item1.description': 'Equipos de última generación para el transporte de cargas excepcionales',
    'equipment.item1.capacity': '1,100 toneladas',
    'equipment.item1.feature1': 'Sistemas hidráulicos avanzados',
    'equipment.item1.feature2': 'Configuración modular',
    'equipment.item1.feature3': 'Control remoto',
    'equipment.item1.feature4': 'Suspensión adaptativa',
    'equipment.item2.name': 'Sistemas Especializados hasta 1100 toneladas',
    'equipment.item2.description': 'Plataformas autopropulsadas de alta precisión para cargas críticas',
    'equipment.item2.capacity': 'hasta 1100 toneladas',
    'equipment.item2.feature1': 'Autopropulsado',
    'equipment.item2.feature2': 'Control de precisión',
    'equipment.item2.feature3': 'Sistemas de navegación',
    'equipment.item2.feature4': 'Operación remota',
    'equipment.item3.name': 'Grúas Móviles Telescópicas hasta 500 toneladas',
    'equipment.item3.description': 'Grúas Móviles de Alta Capacidad para Operaciones de Izamiento Especializado',
    'equipment.item3.capacity': 'hasta 500 toneladas',
    'equipment.item3.feature1': 'Alta movilidad',
    'equipment.item3.feature2': 'Controles digitales',
    'equipment.item3.feature3': 'Operadores certificados',
    'equipment.item4.name': 'Grúas sobre Orugas hasta 800 toneladas',
    'equipment.item4.description': 'Equipos Especializados para Izamiento en Terrenos Difíciles',
    'equipment.item4.capacity': 'hasta 800 toneladas',
    'equipment.item4.feature1': 'Base sobre orugas',
    'equipment.item4.feature2': 'Estabilidad superior',
    'equipment.item4.feature3': 'Alcance extendido',
    'equipment.item4.feature4': 'Configuración versátil',
    'equipment.item5.name': 'Camiones Especializados Variable',
    'equipment.item5.description': 'Alquiler de Flota de Camiones Especializados para Diferentes Tipos de Carga',
    'equipment.item5.capacity': 'Variable',
    'equipment.item5.feature1': 'Alta potencia',
    'equipment.item5.feature2': 'Transmisión especializada',
    'equipment.item5.feature3': 'Sistemas de seguridad',
    'equipment.item5.feature4': 'Mantenimiento preventivo',
    'equipment.item6.name': 'Equipos de Apoyo Diversas',
    'equipment.item6.description': 'Sistemas complementarios para operaciones complejas de transporte',
    'equipment.item6.capacity': 'Diversas',
    'equipment.item6.feature1': 'Sistemas de apoyo',
    'equipment.item6.feature2': 'Equipos auxiliares',
    'equipment.item6.feature3': 'Herramientas especializadas',
    'equipment.item6.feature4': 'Soporte técnico',
    'equipment.specs.button': 'Ver Especificaciones',
    
    // Projects
    'projects.title': 'Proyectos Realizados',
    'projects.subtitle': 'Experiencia comprobada en transporte de cargas excepcionales',
    'projects.1.title': 'Transporte Ferroviario Metro Caracas',
    'projects.1.weight': '280 toneladas',
    'projects.1.sector': 'Transporte Ferroviario',
    'projects.1.location': 'Puerto La Guaira - Caracas',
    'projects.1.description': 'Transporte especializado de vagones del Metro de Caracas con trailers modulares hidráulicos',
    'projects.2.title': 'Equipos Ferroviarios Protegidos',
    'projects.2.weight': '250 toneladas',
    'projects.2.sector': 'Transporte Ferroviario',
    'projects.2.location': 'Puerto Cabello - Interior',
    'projects.2.description': 'Vagones de metro con protección especial durante transporte terrestre',
    'projects.3.title': 'Convoy Ferroviario Multicar',
    'projects.3.weight': '450 toneladas',
    'projects.3.sector': 'Transporte Ferroviario',
    'projects.3.location': 'Operación Nacional',
    'projects.3.description': 'Múltiples vagones transportados simultáneamente con coordinación logística integral',
    'projects.4.title': 'Transporte Carretero Especializado',
    'projects.4.weight': '380 toneladas',
    'projects.4.sector': 'Logística Industrial',
    'projects.4.location': 'Rutas Nacionales',
    'projects.4.description': 'Convoy de transporte de cargas excepcionales por carreteras venezolanas',
    
    // Project CTA buttons
    'projects.cta.1': 'COTIZAR PROYECTO SIMILAR',
    'projects.cta.2': 'VER MÁS PROYECTOS', 
    'projects.cta.3': 'SOLICITAR INFORMACIÓN',
    'projects.cta.4': 'CONTACTAR ESPECIALISTA',
    'projects.cta.5': 'CONOCER CAPACIDADES',
    'projects.cta.6': 'EVALUAR MI CARGA',
    'projects.cta.7': 'PLANIFICAR TRANSPORTE',
    'projects.cta.8': 'CONSULTAR DISPONIBILIDAD',
    'projects.cta.9': 'OBTENER PRESUPUESTO',
    'projects.cta.10': 'ASESORÍA TÉCNICA GRATIS',
    'projects.cta.11': 'ESTUDIOS DE FACTIBILIDAD',
    'projects.cta.12': 'COORDINACIÓN LOGÍSTICA',
    
    // Project stats
    'projects.stats.of': 'de',
    'projects.stats.projects': 'proyectos',
    'projects.stats.years': 'años experiencia',
    'contact.info.address': 'Ubicación',
    'contact.whatsapp': 'Contactar por WhatsApp',
    'contact.address.full': 'Carretera Nacional Maracay Mariara Km 9, Mariara, Edo. Carabobo',
    
    // Footer
    'footer.description': 'Especializados en transporte de cargas excepcionales hasta 1,100 toneladas con trailers modulares hidráulicos. 40 años transportando el futuro de Venezuela con tecnología alemana de vanguardia.',
    
    // Footer sections
    'footer.pages.title': 'Páginas',
    'footer.pages.home': 'Inicio',
    'footer.pages.about': 'Nosotros',
    'footer.pages.services': 'Servicios',
    'footer.pages.projects': 'Proyectos',
    'footer.pages.contact': 'Contacto',
    
    'footer.resources.title': 'Recursos',
    'footer.resources.blog': 'Blog',
    'footer.resources.equipment': 'Equipos',
    'footer.resources.help': 'Centro de Ayuda',
    'footer.resources.specifications': 'Especificaciones',
    'footer.resources.testimonials': 'Testimonios',
    
    'footer.policies.privacy': 'Política de Protección de Datos',
    'footer.policies.security': 'Política de Seguridad Vial Integral',
    'footer.policies.management': 'Política Integrada de Gestión',
    
    'footer.legal.terms': 'Términos de Servicio',
    'footer.legal.privacy': 'Política de Privacidad',
    'footer.legal.cookies': 'Acuerdo de Cookies',
    'footer.legal.security': 'Política de Seguridad',
    
    'footer.social.title': 'Síguenos en',
    'footer.quote.button': 'SOLICITAR COTIZACIÓN',
    'footer.maps.button': 'VER EN GOOGLE MAPS',
    'footer.services.title': 'Servicios',
    'footer.services.transport': 'Transporte Especializado',
    'footer.services.engineering': 'Logística de Ingeniería',
    'footer.services.hydraulic': 'Modulares Hidráulicos',
    'footer.services.cranes': 'Grúas Grove y Liebherr',
    'footer.newsletter.title': 'Suscríbete a nuestro newsletter',
    'footer.newsletter.placeholder': 'Email de trabajo',
    'footer.newsletter.subscribe': 'Subscribirse',
    'footer.copyright': '© 2024 TRANSERVICA, C.A. Todos los derechos reservados.',
    'footer.rif': 'RIF: J-00207776-0 | 40 años transportando el futuro de Venezuela',
    'footer.follow': 'SEGUIR EN REDES',
    
    // Language Switcher
    'language.spanish': 'ESPAÑOL',
    'language.english': 'ENGLISH',
    
    // Blog
    'blog.title': 'TRANSERVICA BLOG',
    'blog.subtitle': 'Noticias y proyectos de transporte especializado',
    'blog.readMore': 'LEER MÁS',
    'blog.backToHome': 'VOLVER AL INICIO',
    'blog.section.badge': 'Blog Corporativo',
    'blog.section.title': 'NOTICIAS TRANSERVICA',
    'blog.section.description': 'Noticias y proyectos de Transporte de Carga Especializado',
    'blog.section.featured': 'Noticias y Proyectos Destacados',
    'blog.section.readFullArticle': 'Leer Artículo Completo',
    'blog.section.newsletter.title': 'Newsletter TRANSERVICA',
    'blog.section.newsletter.description': 'Recibe noticias exclusivas sobre proyectos de transporte especializado, equipos de última generación y normativas del sector',
    'blog.section.newsletter.placeholder': 'Ingresa tu email corporativo',
    'blog.section.newsletter.subscribe': 'Suscribirse al Blog',
    'blog.section.viewAll': 'Ver Todos los Artículos del Blog',
    'blog.section.cta.title': '¿Tienes un Proyecto Especializado?',
    'blog.section.cta.description': '40 años de experiencia nos respaldan. Nuestro equipo de ingenieros está listo para desarrollar la mejor solución logística para tu empresa',
    'blog.section.cta.consult': 'Consultar Proyecto',
    'blog.section.cta.services': 'Ver Servicios',
    
    // Legal Pages
    'legal.terms.title': 'Términos de Servicio',
    'legal.terms.description': 'Condiciones generales que rigen los servicios de transporte especializado de TRANSERVICA, C.A.',
    'legal.privacy.title': 'Política de Privacidad',
    'legal.privacy.description': 'Protección y tratamiento de datos personales en TRANSERVICA, C.A.',
    'legal.cookies.title': 'Acuerdo de Cookies',
    'legal.cookies.description': 'Información sobre el uso de cookies y tecnologías similares en nuestro sitio web',
    'legal.security.title': 'Política de Seguridad',
    'legal.security.description': 'Compromiso integral con la seguridad en transporte de cargas excepcionales',
    
    // Footer
    'footer.copyright': '© 2025 TRANSERVICA C.A. - Todos los Derechos Reservados.',
    'footer.legal.terms': 'Términos de Servicio',
    'footer.legal.privacy': 'Política de Privacidad',
    'footer.legal.cookies': 'Acuerdo de Cookies',
    'footer.legal.security': 'Política de Seguridad'
  },
  en: {
    // Navigation
    'nav.home': 'HOME',
    'nav.services': 'SERVICES',
    'nav.projects': 'PROJECTS',
    'nav.company': 'COMPANY',
    'nav.contact': 'CONTACT',
    'nav.quote': 'QUOTE',
    'nav.blog': 'BLOG',
    
    // Hero Section
    'hero.title': 'Exceptional Heavy Cargo Transportation Venezuela - Specialized in Heavy and Oversized Load Movement',
    'hero.subtitle': '40 YEARS TRANSPORTING VENEZUELA\'S FUTURE',
    'hero.description': 'Specialized in Heavy and Oversized Load Movement up to 1,100 tons with latest generation Hydraulic Modular trailers.',
    'hero.cta': 'REQUEST QUOTE',
    'hero.video': 'WATCH CORPORATE VIDEO',
    
    // Services Section
    'services.title': 'OUR SERVICES',
    'services.subtitle': 'Specialized solutions for exceptional cargo transportation',
    'services.transport.title': 'Exceptional Cargo Transportation',
    'services.transport.description': 'Mobilization of cargo up to 1,100 tons with state-of-the-art hydraulic modular trailers SCHEUERLE and COMETTO.',
    'services.transport.feature1': 'Up to 1,100 tons',
    'services.transport.feature2': 'Modular trailers',
    'services.transport.feature3': 'Specialized routes',
    'services.transport.feature4': 'Specialized escort',
    'services.cranes.title': 'Specialized Crane Lifting',
    'services.cranes.description': 'Lifting services with Mobile Telescopic and Crawler Cranes for complex industrial projects.',
    'services.cranes.feature1': 'Telescopic cranes',
    'services.cranes.feature2': 'Crawler cranes',
    'services.cranes.feature3': 'Precision lifting',
    'services.cranes.feature4': 'Certified operators',
    'services.logistics.title': 'Complete Engineering Logistics',
    'services.logistics.description': 'Comprehensive planning of transportation projects with feasibility studies and multimodal coordination.',
    'services.logistics.feature1': 'Feasibility studies',
    'services.logistics.feature2': 'Route planning',
    'services.logistics.feature3': 'Multimodal coordination',
    'services.logistics.feature4': 'Project management',
    'services.permits.title': 'INTT Permit Management',
    'services.permits.description': 'Complete permit processing with the National Institute of Land Transportation and competent authorities.',
    'services.permits.feature1': 'INTT permits',
    'services.permits.feature2': 'Complete documentation',
    'services.permits.feature3': 'Fast processing',
    'services.permits.feature4': 'Regulatory compliance',
    'services.feasibility.title': 'Technical Feasibility Studies',
    'services.feasibility.description': 'Detailed technical viability analysis to ensure the success of specialized transportation projects.',
    'services.feasibility.feature1': 'Route analysis',
    'services.feasibility.feature2': 'Structural evaluation',
    'services.feasibility.feature3': 'Load studies',
    'services.feasibility.feature4': 'Technical recommendations',
    'services.multimodal.title': 'Multimodal Coordination',
    'services.multimodal.description': 'Integrated land, sea and rail transportation services for international projects.',
    'services.multimodal.feature1': 'Land transportation',
    'services.multimodal.feature2': 'Maritime coordination',
    'services.multimodal.feature3': 'Rail transportation',
    'services.multimodal.feature4': 'International logistics',
    'services.consult': 'Consult',
    'services.quote': 'Quote',
    'services.cta.title': 'Need to Transport Exceptional Cargo?',
    'services.cta.subtitle': 'Let us Evaluate your Project and Offer you the Best Specialized Cargo Transportation Solution',
    'services.cta.quote': 'Request Quote Now',
    'services.cta.call': 'Speak with a Specialist',
    'services.cta': 'REQUEST INFORMATION',
    'services.watch': 'WATCH SERVICES',
    
    // About Section
    'about.title': 'ABOUT TRANSERVICA',
    'about.subtitle': '40 years transporting Venezuela\'s future',
    'about.description': 'We are a Venezuelan company specialized in exceptional cargo transportation with over 4 decades of experience. We feature German SCHEUERLE technology and a highly qualified team to handle the most challenging projects.',
    'about.experience': '40+ Years of Experience',
    'about.projects': '1000+ Successful Projects',
    'about.capacity': '1,100 Tons Capacity',
    'about.equipment': 'German Technology',
    'about.cta': 'LEARN MORE',
    'about.video': 'WATCH CORPORATE VIDEO',
    'about.benefit1.title': 'Exceptional capacity up to 1,100 tons',
    'about.benefit1.desc': 'Latest generation German hydraulic modular equipment.',
    'about.benefit2.title': 'National coverage with proven experience',
    'about.benefit2.desc': '40 years successfully transporting Venezuela\'s future.',
    'about.benefit3.title': 'Comprehensive platform with 24/7 support',
    'about.benefit3.desc': 'Complete tracking and specialists always available.',
    'about.benefit4.title': 'Personalized support with real humans',
    'about.benefit4.desc': 'Dedicated logistics specialists available at any time.',
    'about.mission.title': 'Mission',
    'about.mission.text': 'Providing mobilization and lifting services for oversized cargo through compliance with safety, guarantee and reliability criteria, anticipating and effectively responding to our clients\' needs, ensuring the welfare of our workers and maximizing productivity.',
    'about.vision.title': 'Vision',
    'about.vision.text': 'To be a nationally and internationally recognized company in the provision of mobilization and lifting services for oversized cargo, with qualified personnel, continuous improvement, opportunity utilization and permanent customer satisfaction.',
    'about.cta.title': 'Multiple Exceptional Loads. One Platform. Zero Complications.',
    'about.cta.subtitle': 'Compare heavy and oversized transportation quotes, book instantly and track in real time — all with TRANSERVICA.',
    'about.cta.quote': 'GET INSTANT QUOTE',
    'about.cta.call': 'SPEAK WITH A SPECIALIST',
    
    // Contact Section
    'contact.title': 'Request Your Quote',
    'contact.subtitle': 'Tell us about your project and we will provide you with a personalized solution with the best market proposal.',
    'contact.form.name': 'Name',
    'contact.form.name.placeholder': 'Your full name',
    'contact.form.email': 'Email',
    'contact.form.email.placeholder': 'your@email.com',
    'contact.form.phone': 'Phone',
    'contact.form.phone.placeholder': '+58 424 123 4567',
    'contact.form.company': 'Company',
    'contact.form.company.placeholder': 'Company name',
    'contact.form.cargo': 'Cargo Type',
    'contact.form.cargo.placeholder': 'Select type',
    'contact.form.cargo.industrial': 'Industrial Equipment',
    'contact.form.cargo.machinery': 'Heavy Machinery',
    'contact.form.cargo.turbines': 'Turbines',
    'contact.form.cargo.oil': 'Oil Equipment',
    'contact.form.cargo.naval': 'Naval Construction',
    'contact.form.cargo.others': 'Others',
    'contact.form.weight': 'Estimated Weight (Tons)',
    'contact.form.weight.placeholder': '100',
    'contact.form.origin': 'Origin',
    'contact.form.origin.placeholder': 'Origin city',
    'contact.form.destination': 'Destination',
    'contact.form.destination.placeholder': 'Destination city',
    'contact.form.description': 'Project Description',
    'contact.form.description.placeholder': 'Describe your project, dimensions, special features, required date, etc.',
    'contact.form.message': 'Message',
    'contact.form.submit': 'Request Free Quote',
    'contact.form.sending': 'Sending...',
    'contact.info.title': 'Contact Information',
    'contact.info.phones': 'Main Phones',
    'contact.info.email': 'Corporate Email',
    'contact.info.address': 'Address',
    'contact.address.full': 'National Highway Maracay Mariara Km 9, Mariara, Carabobo State',
    'hero.stats.years': '40',
    'hero.stats.years.title': 'Years of Experience',
    'hero.stats.years.subtitle': 'Leader in specialized transportation',
    'hero.stats.capacity': '1100',
    'hero.stats.capacity.title': 'Tons Capacity',
    'hero.stats.capacity.subtitle': 'Latest generation equipment',
    'hero.stats.reliability': '100%',
    'hero.stats.reliability.title': 'Reliability',
    'hero.stats.reliability.subtitle': 'Successful projects',
    'projects.title': 'Project Gallery',
    'projects.subtitle': 'Over 40 years transporting exceptional cargo up to 1,100 tons. Learn about some of our most outstanding projects carried out with specialized equipment and cutting-edge technology.',
    'equipment.title': 'Our Specialized Equipment for Lifting and Transportation of Exceptional and Oversized Cargo',
    'equipment.subtitle': 'State-of-the-art equipment for specialized transportation with German technology',
    'equipment.cta.title': 'Need Specialized Equipment for Your Project?',
    'equipment.cta.subtitle': 'We have Venezuela\'s most modern fleet for exceptional cargo transportation',
    'equipment.cta.button': 'REQUEST QUOTE',
    
    // FAQ Section
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Solve your doubts about our specialized transportation services',
    'faq.q1': 'What is the maximum load capacity you can transport?',
    'faq.a1': 'Our specialized fleet can transport up to 1,100 tons using state-of-the-art hydraulic modular trailers.',
    'faq.q2': 'What type of permits do I need for my cargo?',
    'faq.a2': 'We handle all the management of special permits, documentation and coordination with competent authorities.',
    'faq.q3': 'Do you cover the entire Venezuelan territory?',
    'faq.a3': 'Yes, we offer specialized transportation services throughout the national territory with optimized routes and comprehensive logistics.',
    'faq.q4': 'What does the transportation service include?',
    'faq.a4': 'It includes route planning, permits, insurance, loading/unloading, specialized escort and real-time monitoring.',
    
    // Equipment items
    'equipment.item1.name': 'Hydraulic Modular Trailers 1,100 tons',
    'equipment.item1.description': 'State-of-the-art equipment for exceptional cargo transportation',
    'equipment.item1.capacity': '1,100 tons',
    'equipment.item1.feature1': 'Advanced hydraulic systems',
    'equipment.item1.feature2': 'Modular configuration',
    'equipment.item1.feature3': 'Remote control',
    'equipment.item1.feature4': 'Adaptive suspension',
    'equipment.item2.name': 'Specialized Systems up to 1100 tons',
    'equipment.item2.description': 'Self-propelled high-precision platforms for critical loads',
    'equipment.item2.capacity': 'up to 1100 tons',
    'equipment.item2.feature1': 'Self-propelled',
    'equipment.item2.feature2': 'Precision control',
    'equipment.item2.feature3': 'Navigation systems',
    'equipment.item2.feature4': 'Remote operation',
    'equipment.item3.name': 'Telescopic Mobile Cranes up to 500 tons',
    'equipment.item3.description': 'High Capacity Mobile Cranes for Specialized Lifting Operations',
    'equipment.item3.capacity': 'up to 500 tons',
    'equipment.item3.feature1': 'High mobility',
    'equipment.item3.feature2': 'Digital controls',
    'equipment.item3.feature3': 'Certified operators',
    'equipment.item4.name': 'Crawler Cranes up to 800 tons',
    'equipment.item4.description': 'Specialized Equipment for Lifting in Difficult Terrain',
    'equipment.item4.capacity': 'up to 800 tons',
    'equipment.item4.feature1': 'Crawler base',
    'equipment.item4.feature2': 'Superior stability',
    'equipment.item4.feature3': 'Extended reach',
    'equipment.item4.feature4': 'Versatile configuration',
    'equipment.item5.name': 'Specialized Trucks Variable',
    'equipment.item5.description': 'Specialized Truck Fleet Rental for Different Types of Cargo',
    'equipment.item5.capacity': 'Variable',
    'equipment.item5.feature1': 'High power',
    'equipment.item5.feature2': 'Specialized transmission',
    'equipment.item5.feature3': 'Safety systems',
    'equipment.item5.feature4': 'Preventive maintenance',
    'equipment.item6.name': 'Support Equipment Various',
    'equipment.item6.description': 'Complementary systems for complex transportation operations',
    'equipment.item6.capacity': 'Various',
    'equipment.item6.feature1': 'Support systems',
    'equipment.item6.feature2': 'Auxiliary equipment',
    'equipment.item6.feature3': 'Specialized tools',
    'equipment.item6.feature4': 'Technical support',
    'equipment.specs.button': 'View Specifications',
    
    // Projects
    'projects.title': 'Completed Projects',
    'projects.subtitle': 'Proven experience in exceptional cargo transportation',
    'projects.1.title': 'Metro Caracas Railway Transport',
    'projects.1.weight': '280 tons',
    'projects.1.sector': 'Railway Transport',
    'projects.1.location': 'Puerto La Guaira - Caracas',
    'projects.1.description': 'Specialized transport of Metro Caracas wagons with hydraulic modular trailers',
    'projects.2.title': 'Protected Railway Equipment',
    'projects.2.weight': '250 tons',
    'projects.2.sector': 'Railway Transport',
    'projects.2.location': 'Puerto Cabello - Interior',
    'projects.2.description': 'Metro wagons with special protection during land transport',
    'projects.3.title': 'Multicar Railway Convoy',
    'projects.3.weight': '450 tons',
    'projects.3.sector': 'Railway Transport',
    'projects.3.location': 'National Operation',
    'projects.3.description': 'Multiple wagons transported simultaneously with comprehensive logistical coordination',
    'projects.4.title': 'Specialized Road Transport',
    'projects.4.weight': '380 tons',
    'projects.4.sector': 'Industrial Logistics',
    'projects.4.location': 'National Routes',
    'projects.4.description': 'Exceptional cargo transport convoy on Venezuelan highways',
    
    // Project CTA buttons
    'projects.cta.1': 'QUOTE SIMILAR PROJECT',
    'projects.cta.2': 'VIEW MORE PROJECTS',
    'projects.cta.3': 'REQUEST INFORMATION',
    'projects.cta.4': 'CONTACT SPECIALIST',
    'projects.cta.5': 'KNOW CAPABILITIES',
    'projects.cta.6': 'EVALUATE MY CARGO',
    'projects.cta.7': 'PLAN TRANSPORT',
    'projects.cta.8': 'CHECK AVAILABILITY',
    'projects.cta.9': 'GET BUDGET',
    'projects.cta.10': 'FREE TECHNICAL ADVICE',
    'projects.cta.11': 'FEASIBILITY STUDIES',
    'projects.cta.12': 'LOGISTICS COORDINATION',
    
    // Project stats
    'projects.stats.of': 'of',
    'projects.stats.projects': 'projects',
    'projects.stats.years': 'years experience',
    
    // Footer
    'footer.description': 'Specialized in exceptional cargo transportation up to 1,100 tons with hydraulic modular trailers. 40 years transporting Venezuela\'s future with cutting-edge German technology.',
    
    // Footer sections
    'footer.pages.title': 'Pages',
    'footer.pages.home': 'Home',
    'footer.pages.about': 'About',
    'footer.pages.services': 'Services',
    'footer.pages.projects': 'Projects',
    'footer.pages.contact': 'Contact',
    
    'footer.resources.title': 'Resources',
    'footer.resources.blog': 'Blog',
    'footer.resources.equipment': 'Equipment',
    'footer.resources.help': 'Help Center',
    'footer.resources.specifications': 'Specifications',
    'footer.resources.testimonials': 'Testimonials',
    
    'footer.policies.privacy': 'Data Protection Policy',
    'footer.policies.security': 'Comprehensive Road Safety Policy',
    'footer.policies.management': 'Integrated Management Policy',
    
    'footer.legal.terms': 'Terms of Service',
    'footer.legal.privacy': 'Privacy Policy',
    'footer.legal.cookies': 'Cookie Agreement',
    'footer.legal.security': 'Security Policy',
    
    'footer.social.title': 'Follow us on',
    'footer.quote.button': 'REQUEST QUOTE',
    'footer.maps.button': 'VIEW ON GOOGLE MAPS',
    'footer.services.title': 'Services',
    'footer.services.transport': 'Specialized Transportation',
    'footer.services.engineering': 'Engineering Logistics',
    'footer.services.hydraulic': 'Hydraulic Modular',
    'footer.services.cranes': 'Grove and Liebherr Cranes',
    'footer.resources.about': 'About Us',
    'footer.resources.docs': 'Technical Documentation',
    'footer.resources.faq': 'FAQs',
    'footer.newsletter.title': 'Subscribe to our newsletter',
    'footer.newsletter.placeholder': 'Work Email',
    'footer.newsletter.subscribe': 'Subscribe',
    'footer.copyright': '© 2024 TRANSERVICA, C.A. All rights reserved.',
    'footer.rif': 'RIF: J-00207776-0 | 40 years transporting Venezuela\'s future',
    'footer.follow': 'FOLLOW ON SOCIAL',
    
    // Language Switcher
    'language.spanish': 'ESPAÑOL',
    'language.english': 'ENGLISH',
    
    // Blog
    'blog.title': 'TRANSERVICA BLOG',
    'blog.subtitle': 'News and specialized transportation projects',
    'blog.readMore': 'READ MORE',
    'blog.backToHome': 'BACK TO HOME',
    'blog.section.badge': 'Corporate Blog',
    'blog.section.title': 'TRANSERVICA NEWS',
    'blog.section.description': 'News and Specialized Cargo Transportation Projects',
    'blog.section.featured': 'Featured News and Projects',
    'blog.section.readFullArticle': 'Read Full Article',
    'blog.section.newsletter.title': 'TRANSERVICA Newsletter',
    'blog.section.newsletter.description': 'Receive exclusive news about specialized transportation projects, cutting-edge equipment and industry regulations',
    'blog.section.newsletter.placeholder': 'Enter your corporate email',
    'blog.section.newsletter.subscribe': 'Subscribe to Blog',
    'blog.section.viewAll': 'View All Blog Articles',
    'blog.section.cta.title': 'Do You Have a Specialized Project?',
    'blog.section.cta.description': '40 years of experience back us up. Our team of engineers is ready to develop the best logistics solution for your company',
    'blog.section.cta.consult': 'Consult Project',
    'blog.section.cta.services': 'View Services',
    
    // Legal Pages
    'legal.terms.title': 'Terms of Service',
    'legal.terms.description': 'General conditions governing specialized transportation services of TRANSERVICA, C.A.',
    'legal.privacy.title': 'Privacy Policy',
    'legal.privacy.description': 'Protection and treatment of personal data at TRANSERVICA, C.A.',
    'legal.cookies.title': 'Cookie Agreement',
    'legal.cookies.description': 'Information about the use of cookies and similar technologies on our website',
    'legal.security.title': 'Security Policy',
    'legal.security.description': 'Comprehensive commitment to safety in exceptional cargo transportation',
    
    // Footer
    'footer.copyright': '© 2025 TRANSERVICA C.A. - All Rights Reserved.',
    'footer.legal.terms': 'Terms of Service',
    'footer.legal.privacy': 'Privacy Policy',
    'footer.legal.cookies': 'Cookie Agreement',
    'footer.legal.security': 'Security Policy'
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('es');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['es']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}