import { sql } from "drizzle-orm";
import { pgTable, text, varchar, timestamp, integer } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

export const users = pgTable("users", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  username: text("username").notNull().unique(),
  password: text("password").notNull(),
});

export const contactRequests = pgTable("contact_requests", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  name: text("name").notNull(),
  email: text("email").notNull(),
  phone: text("phone").notNull(),
  company: text("company"),
  cargoType: text("cargo_type"),
  estimatedWeight: integer("estimated_weight"),
  origin: text("origin"),
  destination: text("destination"),
  description: text("description").notNull(),
  createdAt: timestamp("created_at").defaultNow(),
});

export const contactosRecibidos = pgTable("contactos_recibidos", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  fechaRecibido: timestamp("fecha_recibido").defaultNow().notNull(),
  nombre: text("nombre").notNull(),
  correoContacto: text("correo_contacto").notNull(),
  telefono: text("telefono").notNull(),
  asunto: text("asunto").notNull(),
  mensaje: text("mensaje").notNull(),
  canal: text("canal").notNull().default("web"),
  estado: text("estado").notNull().default("pendiente"),
  correosNotificados: text("correos_notificados").array().notNull(),
});

export const blogs = pgTable("blogs", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  title: text("title").notNull(),
  slug: text("slug").notNull().unique(),
  content: text("content").notNull(),
  excerpt: text("excerpt"),
  metaTitle: text("meta_title"),
  metaDescription: text("meta_description"),
  keywords: text("keywords").array(),
  city: text("city"),
  sector: text("sector"),
  template: text("template"),
  coverImage: text("cover_image"),
  secondaryImages: text("secondary_images").array(),
  ogImage: text("og_image"),
  published: text("published").notNull().default("true"),
  autoGenerated: text("auto_generated").notNull().default("false"),
  views: integer("views").notNull().default(0),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
  publishedAt: timestamp("published_at").defaultNow(),
});

export const insertUserSchema = createInsertSchema(users).pick({
  username: true,
  password: true,
});

export const insertContactRequestSchema = createInsertSchema(contactRequests).omit({
  id: true,
  createdAt: true,
});

export const insertContactoRecibidoSchema = createInsertSchema(contactosRecibidos).omit({
  id: true,
  fechaRecibido: true,
  correosNotificados: true,
}).extend({
  correosNotificados: z.array(z.string()).optional(),
});

export const insertBlogSchema = createInsertSchema(blogs).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
  publishedAt: true,
  views: true,
});

export type InsertUser = z.infer<typeof insertUserSchema>;
export type User = typeof users.$inferSelect;
export type InsertContactRequest = z.infer<typeof insertContactRequestSchema>;
export type ContactRequest = typeof contactRequests.$inferSelect;
export type InsertContactoRecibido = z.infer<typeof insertContactoRecibidoSchema>;
export type ContactoRecibido = typeof contactosRecibidos.$inferSelect;
export type InsertBlog = z.infer<typeof insertBlogSchema>;
export type Blog = typeof blogs.$inferSelect;
